In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

headers = {
    "authority": "www.idealista.com",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "accept-encoding": "gzip, deflate, br, zstd",
    "accept-language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,tr;q=0.6,hu;q=0.5",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "priority": "u=0, i",
    "referer": "https://www.idealista.com/en/",
    "sec-ch-device-memory": "8",
    "sec-ch-ua": '"Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"',
    "sec-ch-ua-arch": '""',
    "sec-ch-ua-full-version-list": '"Google Chrome";v="147.0.7727.119", "Not.A/Brand";v="8.0.0.0", "Chromium";v="147.0.7727.119"',
    "sec-ch-ua-mobile": "?1",
    "sec-ch-ua-model": '"Nexus 5"',
    "sec-ch-ua-platform": '"Android"',
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "same-origin",
    "sec-fetch-user": "?1",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Mobile Safari/537.36",
}

provinces_of_spain = [
    "a-coruna-provincia", "la-rioja", "las-palmas", "alava", "albacete-provincia", "alicante", "almeria-provincia", "asturias", "avila-provincia", "badajoz-provincia",
    "balears-illes", "barcelona-provincia", "burgos-provincia", "caceres-provincia", "cadiz-provincia",
    "ciudad-real-provincia", "cordoba-provincia", "cuenca-provincia", "girona-provincia",
    "granada-provincia", "guadalajara-provincia", "huelva-provincia", "huesca-provincia", "jaen-provincia", "leon-provincia",
    "lleida-provincia", "lugo-provincia", "madrid-provincia", "malaga-provincia", "murcia-provincia", "ourense-provincia",
    "palencia-provincia", "pontevedra-provincia", "salamanca-provincia",
    "santa-cruz-de-tenerife-provincia", "segovia-provincia", "sevilla-provincia", "soria-provincia", "tarragona-provincia",
    "teruel-provincia", "toledo-provincia", "valencia-provincia", "valladolid-provincia", "zamora-provincia",
    "zaragoza-provincia", "cantabria", "castellon", "guipuzcoa", "navarra", "vizcaya"
]

data = []

for province in provinces_of_spain:

    base_url = f"https://www.idealista.com/en/venta-viviendas/{province}/"

    for page in range(1,2): # 60 pages max.
        if page == 1:
            param = "?ordenado-por=fecha-publicacion-desc"
        else:
            param = f"pagina-{str(page)}.htm?ordenado-por=fecha-publicacion-desc"
        #print(base_url + param)
        response = requests.get(base_url + param, headers=headers)
        if response.status_code != 200:
            print('Error', response.status_code)
            break
        soup = BeautifulSoup(response.content, 'html.parser')
        listings = soup.find_all('article', class_='item')

        for listing in listings:
            title = listing.find('a', class_='item-link').get_text(strip=True)
            url = listing.find('a', class_='item-link')['href']
            image = listing.find('img')['src'] if listing.find('img') else None
            estate_type = title.split(' in ')[0]
            address = title.split(' in ')[-1]
            price = int(listing.find('span', class_='item-price').get_text(strip=True).replace('€','').replace(',','').strip())
            details = listing.find_all('span', class_='item-detail')
            area = int(details[1].get_text(strip=True).replace('m²', '').replace(',','').strip()) if len(details) > 1 and 'm²' in details[1].get_text(strip=True) else None
            price_per_m2 = round(price / area) if area else None
            room = int(details[0].get_text(strip=True).replace('bed.', '').strip()) if 'bed' in details[0].get_text(strip=True) else None
            other_details = details[2].get_text(strip=True) if len(details) > 2 else None
            
            data.append({
                'url': "https://www.idealista.com/" + url,
                'title': title,
                'address': address,
                'province': province,
                'estate_tpye' : estate_type,
                'price': price,
                'price_per_m2': price_per_m2,
                'details': details,
                'area': area,
                'room': room,
                'other': other_details,
                'image': image
            })
    
    break

df = pd.DataFrame(data)
df

Error 403

Empty DataFrame
Columns: []
Index: []

In [257]:
from curl_cffi import requests
import re
import json

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
'Accept-Language': 'en-US,en;q=0.9'}

provinces = {'Alicante': 'https://www.fotocasa.es/en/buy/all-the-houses/alicante-province/all-zones/l', 'Almería': 'https://www.fotocasa.es/en/buy/all-the-houses/almeria-province/all-zones/l', 'Asturias': 'https://www.fotocasa.es/en/buy/all-the-houses/asturias-province/all-zones/l', 'Balearic Islands': 'https://www.fotocasa.es/en/buy/all-the-houses/illes-balears-province/all-zones/l', 'Barcelona': 'https://www.fotocasa.es/en/buy/all-the-houses/barcelona-province/all-zones/l', 'Bizkaia': 'https://www.fotocasa.es/en/buy/all-the-houses/bizkaia-province/all-zones/l', 'Cádiz': 'https://www.fotocasa.es/en/buy/all-the-houses/cadiz-province/all-zones/l', 'Cantabria': 'https://www.fotocasa.es/en/buy/all-the-houses/cantabria-province/all-zones/l', 'Castellón': 'https://www.fotocasa.es/en/buy/all-the-houses/castellon-province/all-zones/l', 'Girona': 'https://www.fotocasa.es/en/buy/all-the-houses/girona-province/all-zones/l', 'Granada': 'https://www.fotocasa.es/en/buy/all-the-houses/granada-province/all-zones/l', 'Las Palmas': 'https://www.fotocasa.es/en/buy/all-the-houses/las-palmas-province/all-zones/l', 'Madrid': 'https://www.fotocasa.es/en/buy/all-the-houses/madrid-province/all-zones/l', 'Málaga': 'https://www.fotocasa.es/en/buy/all-the-houseshe-houses/malaga-province/all-zones/l', 'Murcia': 'https://www.fotocasa.es/en/buy/all-the-houses/murcia-province/all-zones/l', 'Santa Cruz de Tenerife': 'https://www.fotocasa.es/en/buy/all-the-houses/santa-cruz-de-tenerife-province/all-zones/l', 'Sevilla': 'https://www.fotocasa.es/en/buy/all-the-houses/sevilla-province/all-zones/l', 'Tarragona': 'https://www.fotocasa.es/en/buy/all-the-houses/tarragona-province/all-zones/l', 'Toledo': 'https://www.fotocasa.es/en/buy/all-the-houses/toledo-province/all-zones/l', 'Valencia': 'https://www.fotocasa.es/en/buy/all-the-houses/valencia-province/all-zones/l'}
coasts = {'Basque Coast': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-vasca/l', 'Costa Blanca': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-blanca/l', 'Costa Brava': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-brava/l', 'Costa Cálida': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-calida/l', 'Costa del Sol': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-del-sol/l', 'Costa da Morte': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-da-morte/l', 'Costa de Almería': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-de-almeria/l', 'Costa de Cantabria': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-de-cantabria/l', 'Costa de Garraf': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-del-garraf/l', 'Costa de la Luz': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-de-la-luz/l', 'Costa de Valencia': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-de-valencia/l', 'Costa del Azahar': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-del-azahar/l', 'Costa del Maresme': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-del-maresme/l', 'Costa Dorada': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-daurada/l', 'Costa Tropical': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-tropical/l', 'Costa Verde': 'https://www.fotocasa.es/en/buy/all-the-houses/area/costa-verde/l', 'Rías Altas': 'https://www.fotocasa.es/en/buy/all-the-houses/area/rias-altas/l', 'Rías Bajas': 'https://www.fotocasa.es/es/comprar/viviendas/area/rias-bajas/l'}

def parse_script_tag(soup):
    
    script = soup.find("script", {"id": "sui-scripts"})
    # Extract the JSON string from window assignment
    raw = script.string
    matches = re.findall(r'JSON\.parse\("(.+?)"\)', raw, re.DOTALL)
    json_str = matches[1]  # 0 = first, 1 = second, 2 = third etc.
    # Unescape the string (it's double-escaped)
    unescaped = json_str.encode("utf-8").decode("unicode_escape")
    data = json.loads(unescaped)
    
    df2 = pd.DataFrame(data["initialSearch"]["result"]["realEstates"])
    # df2 = pd.json_normalize(df2.to_dict(orient='records'))

    columns = [
            'address', 'buildingSubtype', 'buildingType',
            'coordinates', 'date', 'description',
            'detail', 'features', 'id', 'location', 'multimedia',
            'price', 'rawPrice'
    ]

    df2["description"] = df2["description"].str.encode("utf-8", "ignore").str.decode("utf-8")
    # Filter the columns list to include only existing columns in the DataFrame
    existing_columns = [col for col in columns if col in df2.columns]

    df2 = df2[existing_columns]
    return df2

def clean(df2: pd.DataFrame) -> pd.DataFrame:

    df = df2.copy()

    def extract_feature(features, key):
        if isinstance(features, list):
            for f in features:
                if f.get("key") == key:
                    return f.get("value")
        return None

    df["surface"] = df["features"].apply(lambda x: extract_feature(x, "surface"))
    df["bathrooms"] = df["features"].apply(lambda x: extract_feature(x, "bathrooms"))
    df["rooms"] = df["features"].apply(lambda x: extract_feature(x, "rooms"))

    df["url"] = 'www.fotocasa.es' + df["detail"].apply(lambda x: x.get("en-GB") if isinstance(x, dict) else None)

    df["lat"] = df["coordinates"].apply(lambda x: x.get("latitude") if isinstance(x, dict) else None)
    df["lon"] = df["coordinates"].apply(lambda x: x.get("longitude") if isinstance(x, dict) else None)

    def get_first_src(m):
        if isinstance(m, list) and len(m) > 0 and isinstance(m[0], dict):
            return m[0].get("src")
        return None

    df["image"] = df["multimedia"].apply(get_first_src)

    address_df = df["address"].apply(lambda x: x if isinstance(x, dict) else {}).apply(pd.Series)

    df["publish_date"] = df["date"].apply(lambda x: pd.to_datetime(x.get("timestamp"), unit='ms').date() if isinstance(x, dict) else None)

    df = pd.concat([df, address_df], axis=1)
    df["price"] = df["rawPrice"]

    df = df.drop(columns=["features", "detail", "coordinates", "multimedia", "address", "date", "rawPrice"])

    df["description"] = df["description"].apply(lambda x: x.strip().replace("\n", "") if isinstance(x, str) else None)
    df["price_per_m2"] = df.apply(lambda row: row["price"] / row["surface"] if not pd.isna(row["surface"]) and row["surface"] > 0 else None, axis=1).round(2)
    
    df["source"] = "fotocasa.es"
    df["query_date"] = pd.to_datetime("today").date()

    return df

final = []

for province, url in coasts.items():
    for page in range(1, 2): # 30 ads per page
        response = requests.get(url + f"/{str(page)}", headers=headers, params = {'sortType' : 'publicationDate'})
        soup = BeautifulSoup(response.content, 'html.parser')
        dfTemp = parse_script_tag(soup)
        dfTempClean = clean(dfTemp)
        final.append(dfTempClean)

final_df = pd.concat(final, ignore_index=True)
final_df

,buildingSubtype,buildingType,description,id,location,price,surface,bathrooms,rooms,url,...,province,city,cityZone,county,regionLevel1,regionLevel2,upperLevel,price_per_m2,source,query_date
0,SemidetachedHouse,Flat,SE VENDE CHALET PAREADO EN GETXO CON VISTAS MU...,189544948,"Aixerrota Kalea, 12, Santa María de Getxo",1690000.0,NaN,4.0,4.0,www.fotocasa.es/en/buy/home/getxo/heating-park...,...,Bizkaia,Getxo,None,Gran Bilbao,País Vasco,Bizkaia,None,NaN,fotocasa.es,2026-05-01
1,House_Chalet,Flat,"Barrika, cercano a servicios y metro de Urduli...",189533778,Barrika,1075000.0,420.0,7.0,6.0,www.fotocasa.es/en/buy/home/barrika/heating-pa...,...,Bizkaia,Barrika,None,Uribe,País Vasco,Bizkaia,None,2559.52,fotocasa.es,2026-05-01
2,House_Chalet,Flat,¿Soñando con un hogar donde la tranquilidad y ...,189533761,"Barrio Barrio Isuskiza, Plentzia",690000.0,420.0,5.0,6.0,www.fotocasa.es/en/buy/home/plentzia/parking-t...,...,Bizkaia,Plentzia,None,Uribe,País Vasco,Bizkaia,None,1642.86,fotocasa.es,2026-05-01
3,House_Chalet,Flat,Espectacular vivienda ubicada en primera zona ...,189519611,Igeldo,1810000.0,355.0,5.0,3.0,www.fotocasa.es/en/buy/home/donostia-san-sebas...,...,Gipuzkoa,Donostia - San Sebastián,None,Donostialdea - Oarsoldea,País Vasco,Gipuzkoa,None,5098.59,fotocasa.es,2026-05-01
4,SemidetachedHouse,Flat,Descubre este exclusivo chalet pareado en San ...,189517386,Ategorrieta - Ulia,1390000.0,238.0,3.0,5.0,www.fotocasa.es/en/buy/home/donostia-san-sebas...,...,Gipuzkoa,Donostia - San Sebastián,None,Donostialdea - Oarsoldea,País Vasco,Gipuzkoa,None,5840.34,fotocasa.es,2026-05-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,Flat,Flat,AMPLIO PISO EXTERIOR CON VISTAS AL MAR - CALLE...,189538346,"ARAGON, Travesía de Vigo - San Xoán",195000.0,125.0,2.0,4.0,NaN,...,Pontevedra,Vigo,None,Comarca de Vigo,Galicia,Pontevedra,Travesía de Vigo - San Xoán,1560.00,fotocasa.es,2026-05-01
536,Flat,Flat,!!! .. ́ !!!! ¿Buscas un hoga...,189538323,"Rúa da Cal, A Guarda",139500.0,117.0,2.0,3.0,NaN,...,Pontevedra,A Guarda,None,Baixo Miño,Galicia,Pontevedra,None,1192.31,fotocasa.es,2026-05-01
537,Flat,Flat,"Piso de 83 m² ubicado en Vigo, Pontevedra. Se ...",189537646,"Av Castelao, As Travesas - Balaídos",158200.0,83.0,1.0,1.0,NaN,...,Pontevedra,Vigo,None,Comarca de Vigo,Galicia,Pontevedra,As Travesas - Balaídos,1906.02,fotocasa.es,2026-05-01
538,Apartment,Flat,️ Descubre una oportunidad excepcional para in...,189535747,Sanxenxo pueblo,219500.0,45.0,1.0,1.0,NaN,...,Pontevedra,Sanxenxo,None,Salnés,Galicia,Pontevedra,None,4877.78,fotocasa.es,2026-05-01
539,Flat,Flat,Piso totalmente reformado en pleno corazón de ...,189535080,Vilagarcía,240000.0,70.0,1.0,2.0,NaN,...,Pontevedra,Vilagarcía de Arousa,None,Salnés,Galicia,Pontevedra,None,3428.57,fotocasa.es,2026-05-01

In [258]:
df

,buildingSubtype,buildingType,description,id,location,price,rawPrice,surface,bathrooms,rooms,...,province,city,cityZone,county,regionLevel1,regionLevel2,upperLevel,price_per_m2,source,query_date
0,House_Chalet,Flat,Casa con Encanto en el Corazón de Corme.\r\rTr...,189553700,"Rúa Real, Ponteceso",189.000 €,189000.0,227.0,3.0,6.0,...,A Coruña,Ponteceso,None,Bergantiños,Galicia,A Coruña,None,832.599119,fotocasa.es,2026-05-01
1,House_Chalet,Flat,Se vende parcela de 281 m² con vivienda a rest...,189533508,Vimianzo,45.000 €,45000.0,NaN,NaN,NaN,...,A Coruña,Vimianzo,None,Terra de Soneira,Galicia,A Coruña,None,NaN,fotocasa.es,2026-05-01
2,CountryHouse,Flat,En un entorno rural con todo el encanto de Gal...,189450861,"Asalo, 13, Malpica de Bergantiños",139.990 €,139990.0,202.0,2.0,2.0,...,A Coruña,Malpica de Bergantiños,None,Bergantiños,Galicia,A Coruña,None,693.019802,fotocasa.es,2026-05-01
3,SemidetachedHouse,Flat,,189418971,"Rúa da Altamira, 23, Malpica de Bergantiños",50.000 €,50000.0,92.0,NaN,NaN,...,A Coruña,Malpica de Bergantiños,None,Bergantiños,Galicia,A Coruña,None,543.478261,fotocasa.es,2026-05-01
4,House_Chalet,Flat,OPORTUNIDAD EN CORME A SOLO 170 METROS DE LA P...,189396674,Ponteceso,119.990 €,119990.0,153.0,2.0,8.0,...,A Coruña,Ponteceso,None,Bergantiños,Galicia,A Coruña,None,784.248366,fotocasa.es,2026-05-01
5,House_Chalet,Flat,¿Estás buscando una casa para restaurar a tu g...,189391006,"Vigo, 9, Malpica de Bergantiños",146.000 €,146000.0,360.0,1.0,3.0,...,A Coruña,Malpica de Bergantiños,None,Bergantiños,Galicia,A Coruña,None,405.555556,fotocasa.es,2026-05-01
6,House_Chalet,Flat,"Si buscas vivir en un entorno rural, en un lug...",189390335,"N/A, -1, Malpica de Bergantiños",160.000 €,160000.0,280.0,1.0,4.0,...,A Coruña,Malpica de Bergantiños,None,Bergantiños,Galicia,A Coruña,None,571.428571,fotocasa.es,2026-05-01
7,House_Chalet,Flat,Se vende casa para rehabilitación integral en ...,189387844,Ponteceso,23.600 €,23600.0,135.0,NaN,NaN,...,A Coruña,Ponteceso,None,Bergantiños,Galicia,A Coruña,None,174.814815,fotocasa.es,2026-05-01
8,House_Chalet,Flat,Se ofrece vivienda con reforma integral inclui...,189343794,Malpica de Bergantiños,75.000 €,75000.0,56.0,2.0,4.0,...,A Coruña,Malpica de Bergantiños,None,Bergantiños,Galicia,A Coruña,None,1339.285714,fotocasa.es,2026-05-01
9,House_Chalet,Flat,Descubre esta magnífica vivienda unifamiliar d...,189320293,"BARDULLAS, Muxía",495.000 €,495000.0,436.0,3.0,5.0,...,A Coruña,Muxía,None,Comarca de Fisterra,Galicia,A Coruña,None,1135.321101,fotocasa.es,2026-05-01
10,House_Chalet,Flat,Ubicada en primera línea de playa en Camariñas...,189279892,Camariñas,350.000 €,350000.0,115.0,1.0,4.0,...,A Coruña,Camariñas,None,Terra de Soneira,Galicia,A Coruña,None,3043.478261,fotocasa.es,2026-05-01
11,House_Chalet,Flat,"Casa en Corme , dispone de 3 dormitorios, 1 ba...",189207233,"Estrada Corme-Ponteceso, 11, Ponteceso",85.000 €,85000.0,NaN,NaN,NaN,...,A Coruña,Ponteceso,None,Bergantiños,Galicia,A Coruña,None,NaN,fotocasa.es,2026-05-01
12,SemidetachedHouse,Flat,Encantadora casa de piedra de dos plantas para...,189151797,"Rua Vilar, 11, Vimianzo",59.900 €,59900.0,NaN,NaN,2.0,...,A Coruña,Vimianzo,None,Terra de Soneira,Galicia,A Coruña,None,NaN,fotocasa.es,2026-05-01
13,SemidetachedHouse,Flat,Casa en venta en Buño (Malpica) – 228 m² – Ter...,189112965,"N/A, -1, Malpica de Bergantiños",95.000 €,95000.0,228.0,2.0,3.0,...,A Coruña,Malpica de Bergantiños,None,Bergantiños,Galicia,A Coruña,None,416.666667,fotocasa.es,2026-05-01
14,CountryHouse,Flat,"Este impresionante complejo turístico, complet...",189101263,Malpica de Bergantiños,635.000 €,635000.0,445.0,NaN,11.0,...,A Coruña,Malpica de Bergantiños,None,Bergantiños,Galicia,A Coruña,None,1426.966292,fotocasa.es,2026-05-01
15,House_Chalet,Flat,Se vende casa para rehabilitación integral sit...,189034057,Ponteceso,49.500 €,49500.0,233.0,1.0,3.0,...,A Coruña,Ponteceso,None,Bergantiños,Galicia,A Coruña,None,212.446352,fotocasa.es,2026-05-01
16,House_Chalet,Flat,Vivir a menos de 100 metros de la playa y con ...,188922377,Laxe,265.000 €,265000.0,319.0,3.0,7.0,...,A Coruña,Laxe,None,Bergantiños,Galicia,A Coruña,None,830.721003,fotocasa.es,2026-05-01
17,House_Chalet,Flat,Vendemos vivienda unifamiliar de 224 m² constr...,188884330,"N/A, Cabana de Bergantiños",182.000 €,182000.0,224.0,3.0,5.0,...,A Coruña,Cabana de Bergantiños,None,Bergantiños,Galicia,A Coruña,None,812.500000,fotocasa.es,2026-05-01
18,CountryHouse,Flat,"“Restaurar un sueño, vivir un lugar.” Edifica...",188878691,Camariñas,75.000 €,75000.0,252.0,NaN,1.0,...,A Coruña,Camariñas,None,Terra de Soneira,Galicia,A Coruña,None,297.619048,fotocasa.es,2026-05-01
19,House_Chalet,Flat,Casa independiente con finca en entorno rural ...,188867025,Muxía,145.000 €,145000.0,197.0,1.0,3.0,...,A Coruña,Muxía,None,Comarca de Fisterra,Galicia,A Coruña,None,736.040609,fotocasa.es,2026-05-01
20,House_Chalet,Flat,¡ Oportunidad ! ¡ Con 9 dormitorios ! Amplia ...,188853904,"LG Aspera ASPERA, Cabana de Bergantiños",165.000 €,165000.0,224.0,NaN,9.0,...,A Coruña,Cabana de Bergantiños,None,Bergantiños,Galicia,A Coruña,None,736.607143,fotocasa.es,2026-05-01
21,House_Chalet,Flat,"Si buscas una propiedad amplia, con muchísimas...",188774210,Vimianzo,129.900 €,129900.0,503.0,5.0,6.0,...,A Coruña,Vimianzo,None,Terra de Soneira,Galicia,A Coruña,None,258.250497,fotocasa.es,2026-05-01
22,House_Chalet,Flat,Se vende casa con finca anexa en Vilaseco (Vim...,188764942,Vimianzo,None,NaN,60.0,1.0,3.0,...,A Coruña,Vimianzo,None,Terra de Soneira,Galicia,A Coruña,None,NaN,fotocasa.es,2026-05-01
23,House_Chalet,Flat,"Chalet con bajo y dos plantas, en el bajo hay ...",188730113,"Estrada Buño Laxe, 74, Cabana de Bergantiños",525.000 €,525000.0,408.0,3.0,6.0,...,A Coruña,Cabana de Bergantiños,None,Bergantiños,Galicia,A Coruña,None,1286.764706,fotocasa.es,2026-05-01
24,House_Chalet,Flat,"Casa independiente cerrada de muro, para entra...",188716717,"Aldea, 60, Ponteceso",195.000 €,195000.0,268.0,1.0,4.0,...,A Coruña,Ponteceso,None,Bergantiños,Galicia,A Coruña,None,727.611940,fotocasa.es,2026-05-01
25,House_Chalet,Flat,Casa Rural para Reformar en la parroquia de Mo...,188659440,Muxía,150.000 €,150000.0,296.0,1.0,4.0,...,A Coruña,Muxía,None,Comarca de Fisterra,Galicia,A Coruña,None,506.756757,fotocasa.es,2026-05-01
26,House_Chalet,Flat,"Si buscas una casa amplia, cerca de la playa y...",188644082,Malpica de Bergantiños,249.990 €,249990.0,510.0,3.0,3.0,...,A Coruña,Malpica de Bergantiños,None,Bergantiños,Galicia,A Coruña,None,490.176471,fotocasa.es,2026-05-01
27,CountryHouse,Flat,"EN PLENA COSTA DA MORTE, A 30 MINUTOS DE A COR...",188603908,Malpica de Bergantiños,274.900 €,274900.0,239.0,2.0,6.0,...,A Coruña,Malpica de Bergantiños,None,Bergantiños,Galicia,A Coruña,None,1150.209205,fotocasa.es,2026-05-01
28,House_Chalet,Flat,Casa rústica con huerto y hórreo a 2km de la p...,188513560,"Travesía Fenllido, 10, Laxe",230.000 €,230000.0,400.0,3.0,7.0,...,A Coruña,Laxe,None,Bergantiños,Galicia,A Coruña,None,575.000000,fotocasa.es,2026-05-01
29,House_Chalet,Flat,¡Tu sueño de hogar junto al mar se hace realid...,188483411,"Lugar Boaño, Laxe",225.000 €,225000.0,342.0,NaN,NaN,...,A Coruña,Laxe,None,Bergantiños,Galicia,A Coruña,None,657.894737,fotocasa.es,2026-05-01

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
'Accept-Language': 'en-US,en;q=0.9',
'Accept-Encoding': 'gzip, deflate, br'}

portgual_districts = [
    "aveiro-distrito", "beja-distrito", "braga-distrito", "braganca-distrito", "castelo-branco-distrito",
    "coimbra-distrito", "evora-distrito", "faro-distrito", "guarda-distrito", "leiria-distrito", "lisboa-distrito",
    "portalegre-distrito", "porto-distrito", "santarem-distrito", "setubal-distrito", "viana-do-castelo-distrito",
    "vila-real-distrito", "viseu-distrito","acores", "madeira-ilha"
]

data = []

for district in portgual_districts:

    base_url = f"https://www.idealista.pt/en/comprar-casas/{district}/"

    for page in range(1,60): # 60 pages max.
        if page == 1:
            param = "?ordem=atualizado-desc"
        else:
            param = f"pagina-{str(page)}?ordem=atualizado-desc"
        print(base_url + param)
        if district == "acores":
            response = requests.get(f"https://www.idealista.pt/en/geo/comprar-casas/{district}/" + param, headers=headers, timeout=10)
            time.sleep(2)
        else:
            try:
                response = requests.get(base_url + param, headers=headers, timeout=10)
            except (ConnectionError, requests.exceptions.ReadTimeout):
                print('ConnectionError')
                continue
        if response.status_code != 200:
            print('Error', response.status_code)
            break
        soup = BeautifulSoup(response.content, 'html.parser')
        listings = soup.find_all('article', class_='item')

        for listing in listings:
            title = listing.find('a', class_='item-link').get_text(strip=True)
            url = listing.find('a', class_='item-link')['href']
            image = listing.find('img')['src'] if listing.find('img') else None
            estate_type = title.split(' in ')[0]
            address = title.split(' in ')[-1]
            price = int(listing.find('span', class_='item-price').get_text(strip=True).replace('€','').replace(',','').strip())
            details = listing.find_all('span', class_='item-detail')
            area = int(details[1].get_text(strip=True).replace('m²', '').replace(',','').strip()) if len(details) > 1 and 'm²' in details[1].get_text(strip=True) else None
            price_per_m2 = round(price / area) if area else None
            room = int(details[0].get_text(strip=True).replace('T', '').strip()) if 'T' in details[0].get_text(strip=True) else None
            other_details = details[2].get_text(strip=True) if len(details) > 2 else None
            
            data.append({
                'url': "https://www.idealista.pt" + url,
                'title': title,
                'address': address,
                'district': district,
                'estate_tpye' : estate_type,
                'price': price,
                'price_per_m2': price_per_m2,
                'details': details,
                'area': area,
                'room': room,
                'other': other_details,
                'image': image
            })
        

df = pd.DataFrame(data)
df

https://www.idealista.pt/en/comprar-casas/aveiro-distrito/?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-2?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-3?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-4?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-5?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-6?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-7?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-8?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-9?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-10?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-11?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-12?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-13?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-14?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-15?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-16?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-17?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-18?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-19?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-20?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-21?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-22?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-23?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-24?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-25?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-26?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-27?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-28?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-29?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-30?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-31?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-32?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-33?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-34?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-35?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-36?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-37?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-38?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-39?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-40?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-41?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-42?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-43?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-44?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-45?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-46?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-47?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-48?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-49?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-50?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-51?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-52?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-53?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-54?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-55?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-56?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-57?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-58?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/aveiro-distrito/pagina-59?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-2?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-3?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-4?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-5?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-6?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-7?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-8?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-9?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-10?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-11?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-12?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-13?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-14?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-15?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-16?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-17?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-18?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-19?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-20?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-21?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-22?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-23?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-24?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-25?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-26?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-27?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-28?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-29?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-30?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-31?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-32?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-33?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-34?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-35?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-36?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-37?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-38?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-39?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-40?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-41?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-42?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-43?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-44?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-45?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-46?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-47?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-48?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-49?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-50?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-51?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-52?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-53?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-54?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-55?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-56?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-57?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-58?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/beja-distrito/pagina-59?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-2?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-3?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-4?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-5?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-6?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-7?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-8?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-9?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-10?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-11?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-12?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-13?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-14?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-15?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-16?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-17?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-18?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-19?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-20?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-21?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-22?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-23?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-24?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-25?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-26?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-27?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-28?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-29?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-30?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-31?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-32?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-33?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-34?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-35?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-36?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-37?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-38?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-39?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-40?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-41?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-42?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-43?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-44?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-45?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-46?ordem=atualizado-desc
ConnectionError
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-47?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-48?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-49?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-50?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-51?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-52?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-53?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-54?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-55?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-56?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-57?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-58?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braga-distrito/pagina-59?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-2?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-3?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-4?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-5?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-6?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-7?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-8?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-9?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-10?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-11?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-12?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-13?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-14?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-15?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-16?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-17?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-18?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-19?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-20?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-21?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-22?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-23?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-24?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-25?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-26?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-27?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-28?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-29?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-30?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-31?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-32?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-33?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-34?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-35?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-36?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-37?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-38?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-39?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-40?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-41?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-42?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-43?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-44?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-45?ordem=atualizado-desc
https://www.idealista.pt/en/comprar-casas/braganca-distrito/pagina-46?ordem=atualizado-desc

,url,title,address,district,estate_tpye,price,price_per_m2,details,area,room,other,image
0,https://www.idealista.pt/en/imovel/33795411/,"Semi-detached house in São Salvador, Ílhavo","São Salvador, Ílhavo",aveiro-distrito,Semi-detached house,189900,2261,"[[T2 ], [84 m²]]",84,2,None,https://img4.idealista.pt/blur/WEB_LISTING-M/0...
1,https://www.idealista.pt/en/imovel/33795308/,"T1 flat in São Salvador, Ílhavo","São Salvador, Ílhavo",aveiro-distrito,T1 flat,220000,2340,"[[T1 ], [94 m²], [ without lift]]",94,1,without lift,https://st3.idealista.pt/cf/09/84/ville-real-e...
2,https://www.idealista.pt/en/imovel/33795291/,"T2 flat in São Salvador, Ílhavo","São Salvador, Ílhavo",aveiro-distrito,T2 flat,290000,2417,"[[T2 ], [120 m²], [ without lift]]",120,2,without lift,https://img4.idealista.pt/blur/WEB_LISTING-M/0...
3,https://www.idealista.pt/en/imovel/33795307/,"T1 flat in Esgueira, Aveiro","Esgueira, Aveiro",aveiro-distrito,T1 flat,225000,2228,"[[T1 ], [101 m²], [ with lift]]",101,1,with lift,https://img4.idealista.pt/blur/WEB_LISTING-M/0...
4,https://www.idealista.pt/en/imovel/33795303/,"Detached house in Aradas, Aveiro","Aradas, Aveiro",aveiro-distrito,Detached house,319000,1564,"[[T4 ], [204 m²]]",204,4,None,https://img4.idealista.pt/blur/WEB_LISTING-M/0...
...,...,...,...,...,...,...,...,...,...,...,...,...
35222,https://www.idealista.pt/en/imovel/33596496/,"T2 flat in rua da olaria, 32, Caniço, Santa Cruz","rua da olaria, 32, Caniço, Santa Cruz",madeira-ilha,T2 flat,259500,3816,"[[T2 ], [68 m²], [2nd floor with lift]]",68,2,2nd floor with lift,https://img4.idealista.pt/blur/WEB_LISTING-M/0...
35223,https://www.idealista.pt/en/imovel/33596736/,"T2 flat in Virtudes - Barreiros, São Martinho","Virtudes - Barreiros, São Martinho",madeira-ilha,T2 flat,525000,3344,"[[T2 ], [157 m²], [3rd floor ]]",157,2,3rd floor,https://img4.idealista.pt/blur/WEB_LISTING-M/0...
35224,https://www.idealista.pt/en/imovel/33565237/,"Detached house in estrada da Boa Nova, Santa M...","estrada da Boa Nova, Santa Maria Maior, Funchal",madeira-ilha,Detached house,1690000,4568,"[[T3 ], [370 m²]]",370,3,None,https://img4.idealista.pt/blur/WEB_LISTING-M/0...
35225,https://www.idealista.pt/en/imovel/33596488/,"Terraced house in rua Encosta dos Magos, Caniç...","rua Encosta dos Magos, Caniço, Santa Cruz",madeira-ilha,Terraced house,298000,1568,"[[T2 ], [190 m²]]",190,2,None,https://img4.idealista.pt/blur/WEB_LISTING-M/0...
35226,https://www.idealista.pt/en/imovel/33580255/,"Detached house in caminho da Relva, Arco da Ca...","caminho da Relva, Arco da Calheta, Calheta (Ma...",madeira-ilha,Detached house,320000,1391,"[[T3 ], [230 m²]]",230,3,None,https://img4.idealista.pt/blur/WEB_LISTING-M/0...

In [4]:
df.to_csv("real_estate_portugal.csv", sep=";", index=False, encoding="utf-8-sig")

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
'Accept-Language': 'en-US,en;q=0.9',
'Accept-Encoding': 'gzip, deflate, br'}

italy_provinces = ['agrigento-provincia', 'alessandria-provincia', 'alpi-marittime-costa-azzurra', 'ancona-provincia',
                   'aosta-provincia', 'arezzo-provincia', 'ascoli-piceno-provincia', 'asti-provincia',
                   'avellino-provincia', 'bari-provincia', 'barletta-andria-trani', 'belluno-provincia',
                   'benevento-provincia', 'bergamo-provincia', 'biella-provincia', 'bologna-provincia',
                   'bolzano-bozen-provincia', 'brescia-provincia', 'brindisi-provincia', 'cagliari-provincia',
                   'caltanissetta-provincia', 'campobasso-provincia', 'canton-ticino', 'caserta-provincia', 'catania-provincia',
                   'catanzaro-provincia', 'chieti-provincia', 'como-provincia', 'cosenza-provincia', 'cremona-provincia',
                   'crotone-provincia', 'cuneo-provincia', 'enna-provincia', 'fermo-provincia', 'ferrara-provincia',
                   'firenze-provincia', 'foggia-provincia', 'forli-cesena', 'frosinone-provincia', 'genova-provincia',
                   'gorizia-provincia', 'grosseto-provincia', 'imperia-provincia', 'isernia-provincia', 'l-aquila-provincia',
                   'la-spezia-provincia', 'latina-provincia', 'lecce-provincia', 'lecco-provincia', 'livorno-provincia',
                   'lodi-provincia', 'lucca-provincia', 'macerata-provincia', 'mantova-provincia', 'massa-carrara',
                   'matera-provincia', 'messina-provincia', 'milano-provincia', 'modena-provincia', 'monza-brianza',
                   'napoli-provincia', 'novara-provincia', 'nuoro-provincia', 'oristano-provincia', 'padova-provincia',
                   'palermo-provincia', 'parma-provincia', 'pavia-provincia', 'perugia-provincia', 'pesaro-urbino',
                   'pescara-provincia', 'piacenza-provincia', 'pisa-provincia', 'pistoia-provincia', 'pordenone-provincia',
                   'potenza-provincia', 'prato-provincia', 'ragusa-provincia', 'ravenna-provincia', 'reggio-calabria-provincia',
                   'reggio-emilia-provincia', 'rieti-provincia', 'rimini-provincia', 'roma-provincia', 'rovigo-provincia',
                   'salerno-provincia', 'san-marino-provincia', 'sassari-provincia', 'savona-provincia', 'siena-provincia',
                   'sondrio-provincia', 'sud-sardegna', 'siracusa-provincia', 'taranto-provincia', 'teramo-provincia',
                   'terni-provincia', 'trapani-provincia', 'trento-provincia', 'treviso-provincia', 'trieste-provincia',
                   'torino-provincia', 'udine-provincia', 'varese-provincia', 'venezia-provincia', 'verbano-cusio-ossola',
                   'vercelli-provincia', 'verona-provincia', 'vibo-valentia-provincia', 'vicenza-provincia', 'viterbo-provincia']

data = []

for province in italy_provinces:

    base_url = f"https://www.idealista.it/en/vendita-case/{province}/"

    for page in range(1,2): # 60 pages max.
        if page == 1:
            param = "?ordine=pubblicazione-desc"
        else:
            param = f"lista-{str(page)}.htm?ordine=pubblicazione-desc"
        print(base_url + param)
        response = requests.get(base_url + param, headers=headers)
        time.sleep(2)
        if response.status_code != 200:
            print('Error', response.status_code)
            break
        soup = BeautifulSoup(response.content, 'html.parser')
        listings = soup.find_all('article', class_='item')

        for listing in listings:
            title = listing.find('a', class_='item-link').get_text(strip=True)
            url = listing.find('a', class_='item-link')['href']
            image = listing.find('img')['src'] if listing.find('img') else None
            estate_type = title.split(' in ')[0]
            address = title.split(' in ')[-1]
            price = int(listing.find('span', class_='item-price').get_text(strip=True).replace('€','').replace(',','').strip())
            details = listing.find_all('span', class_='item-detail')
            area = int(details[1].get_text(strip=True).replace('m²', '').replace(',','').strip()) if len(details) > 1 and 'm²' in details[1].get_text(strip=True) else None
            price_per_m2 = round(price / area) if area else None
            room = int(details[0].get_text(strip=True).replace('rooms', '').strip()) if 'rooms' in details[0].get_text(strip=True) else None
            other_details = details[2].get_text(strip=True) if len(details) > 2 else None
            
            data.append({
                'url': "https://www.idealista.it" + url,
                'title': title,
                'address': address,
                'province': province,
                'estate_tpye' : estate_type,
                'price': price,
                'price_per_m2': price_per_m2,
                'details': details,
                'area': area,
                'room': room,
                'other': other_details,
                'image': image
            })

df = pd.DataFrame(data)
df

https://www.idealista.it/en/vendita-case/agrigento-provincia/?ordine=pubblicazione-desc
Error 403
https://www.idealista.it/en/vendita-case/alessandria-provincia/?ordine=pubblicazione-desc

KeyboardInterrupt:

In [ ]:
#FAILED to parse IMMOWEB

import requests
from bs4 import BeautifulSoup
import pandas as pd
import json

# Define the URL of the Immoweb search page
url = 'https://www.immoweb.be/en/search/apartment/for-sale?countries=BE&page=1&orderBy=newest'

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
'Accept-Language': 'en-US,en;q=0.9',
'Accept-Encoding': 'gzip, deflate, br'}

# Send a GET request to the URL
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.content, 'html.parser')
listings = soup.find_all('article', class_='card--result')

data = []

for listing in listings:
    title = listing.find('h2', class_='card__title').get_text(strip=True)
    # price = listing.find('p', class_='card--result__price').get_text(strip=True)
    # click_attr = listing.find("a")["@click"]
    # json_str = click_attr[click_attr.find("{"):click_attr.rfind("}")+1].replace('\\"', '\\\\"').replace('\\/', '/')#.replace('aria-hidden="true"', 'aria-hidden=\\"true\\"')
    # json_data = json.loads(json_str)
    # price = json_data["price"]["accessibilityPrice"]
    location = listing.find('p', class_='card__information card--results__information--locality').get_text(strip=True)
    details = listing.find('div', class_='card__informations').get_text(strip=True)
    url = listing.find('a', class_='card__title-link')['href']
    image = listing.find('img', class_='card__media-picture')['src']
    bedrooms_tag = listing.find('span', class_='sr-only')
    bedrooms = bedrooms_tag.text.split("-")[-1].split()[0].strip() if bedrooms_tag else None
    area_tag = listing.find('p', class_='card__information card--result__information card__information--property')
    area = area_tag.text.replace('\n', '').replace('·', '').strip() if area_tag else None

    # Parse price, lower boundary and convert to int
    #price = int(price.split('€')[1].split('-')[0].replace(',', '').strip()) if price else None

    data.append({
        'title': title,
        'price': price,
        'location': location,
        'details': details,
        'url': url,
        'image': image,
        'bedrooms': bedrooms,
        'area': area
    })
# Create a DataFrame from the data
df = pd.DataFrame(data)

df

In [181]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Define the URL of the Bienici search page
url = 'https://www.bienici.com/recherche/achat/france?mode=liste&tri=publication-desc'

# Send a GET request to the URL
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

# Find all listings
listings = soup.find_all('article', class_='sideListItem')

data = []

for listing in listings:
    title = listing.find('h2', class_='c-pa-link').get_text(strip=True)
    price = listing.find('div', class_='c-pa-price').get_text(strip=True)
    location = listing.find('div', class_='c-pa-city').get_text(strip=True)
    details = listing.find('div', class_='c-pa-criterion').get_text(strip=True)
    url = listing.find('a', class_='c-pa-link')['href']
    image = listing.find('img', class_='c-pa-image')['src'] if listing.find('img', class_='c-pa-image') else None

    data.append({
        'title': title,
        'price': price,
        'location': location,
        'details': details,
        'url': url,
        'image': image
    })

# Create a DataFrame from the data
df = pd.DataFrame(data)

print(df)

Empty DataFrame
Columns: []
Index: []

In [17]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.rightmove.co.uk/major-cities.html"

response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

cities = soup.find_all('section', class_='majorCities_linkGroup__Vkdnk')
cities = [city.find("a")["href"] for city in cities]

# Define the URL of the Rightmove search page
baseUrl = 'https://www.rightmove.co.uk'
# Send a GET request to the URL
data = []

for city in cities:
    for page in range(1,4):
        response = requests.get(baseUrl + city + f'?index={str(page*24)}&sortType=6')
        soup = BeautifulSoup(response.content, 'html.parser')

        # Find all listings
        listings = soup.find_all('div', class_='l-searchResult is-list')

        for listing in listings:
            title = listing.find('h2', class_='propertyCard-title').get_text(strip=True)
            price = listing.find('div', class_='propertyCard-priceValue').get_text(strip=True)
            location = listing.find('address', class_='propertyCard-address').get_text(strip=True)
            details = listing.find('div', class_='propertyCard-description').get_text(strip=True)
            #information = listing.find('div', class_='property-information').get_text(strip=True) if listing.find('div', class_='property-information') else None
            url = listing.find('a', class_='propertyCard-link')['href']
            image = listing.find('div', class_='propertyCard-img').find('img')['src'] if listing.find('div', class_='propertyCard-img') else None

            data.append({
                'title': title,
                'price': price,
                'location': location,
                'details': details,
                #'information': information,
                'url': 'https://www.rightmove.co.uk' + url,
                'image': image,
                'city': city.split('/')[-1].replace('.hmtl', ''),
                'source': 'rightmove'
            })
        

# Create a DataFrame from the data
df = pd.DataFrame(data)

df

c:\PythonScripting\Applications\Mambaforge\envs\_scripting310w\lib\site-packages\bs4\__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(

,title,price,location,details,url,image,city,source
0,3 bedroom detached house for sale,"£565,000","Cherry Square,\r\nBasingstoke,\r\nRG23 7PX",SHOW HOME AVAILABLE TO VIEW. Welcome to the Wi...,https://www.rightmove.co.uk/properties/1541381...,https://media.rightmove.co.uk:443/dir/crop/10:...,Basingstoke.html,rightmove
1,5 bedroom detached house for sale,"£800,000","Heritage Park, Hatch Warren",This elegant home has been thoughtfully extend...,https://www.rightmove.co.uk/properties/1553279...,https://media.rightmove.co.uk:443/dir/crop/10:...,Basingstoke.html,rightmove
2,2 bedroom mobile home for sale,"£200,000","Hatch Park, London Road, Old Basing, Basingsto...",Hatch Park is part of a private residential co...,https://www.rightmove.co.uk/properties/1548397...,https://media.rightmove.co.uk:443/dir/crop/10:...,Basingstoke.html,rightmove
3,2 bedroom terraced house for sale,"£275,000","Sorrells Close, Chineham, Basingstoke, Hampshi...",EweMove - This charming 2-bedroom house is sit...,https://www.rightmove.co.uk/properties/1553220...,https://media.rightmove.co.uk:443/dir/crop/10:...,Basingstoke.html,rightmove
4,2 bedroom maisonette for sale,"£210,000","Basingstoke, Hampshire, RG21",This is a two bedroom Ground floor maisonette ...,https://www.rightmove.co.uk/properties/1545548...,https://media.rightmove.co.uk:443/dir/crop/10:...,Basingstoke.html,rightmove
...,...,...,...,...,...,...,...,...
5095,2 bedroom apartment for sale,"£475,000","Bishopthorpe Road, York",SOUTH FACING BALCONY AND CITY CENTRE VIEWS! Th...,https://www.rightmove.co.uk/properties/1550949...,https://media.rightmove.co.uk:443/dir/crop/10:...,York.html,rightmove
5096,3 bedroom detached house for sale,"£375,000","Kirkdale Road, York",Located in the popular residential area of Osb...,https://www.rightmove.co.uk/properties/1550944...,https://media.rightmove.co.uk:443/dir/crop/10:...,York.html,rightmove
5097,3 bedroom house for sale,"£305,000","Aldborough Way, Off Leeman Road",NO ONWARD CHAIN! A MODERN THREE BEDROOM END OF...,https://www.rightmove.co.uk/properties/1509249...,https://media.rightmove.co.uk:443/dir/crop/10:...,York.html,rightmove
5098,3 bedroom semi-detached house for sale,"£650,000","Middlethorpe Drive, York","This substantial, extended semi-detached home ...",https://www.rightmove.co.uk/properties/1546759...,https://media.rightmove.co.uk:443/dir/crop/10:...,York.html,rightmove
5099,4 bedroom link detached house for sale,"£625,000","Plot 40 Cocoa Gardens, Wigginton Road, York, YO31",The Marketing Suite is now open 7 days a week ...,https://www.rightmove.co.uk/properties/1550920...,https://media.rightmove.co.uk:443/dir/crop/10:...,York.html,rightmove

In [18]:
df.to_csv("real_estate_uk.csv", sep=";", index=False, encoding="utf-8-sig")

In [69]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import random

headers_list = [
    {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
        'Accept-Encoding': 'gzip, deflate, br',
        'Connection': 'keep-alive'
    },
    {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br'
    },
    {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br',
        'Connection': 'keep-alive'
    },
    {
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br'
    },
    {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
        'Accept-Encoding': 'gzip, deflate, br'
    },
    {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br'
    },
    {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br',
        'Connection': 'keep-alive'
    },
    {
        'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br'
    },
    {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br',
        'Connection': 'keep-alive'
    },
    {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
        'Accept-Encoding': 'gzip, deflate, br'
    }
]

headers = random.choice(headers_list)

data = []

for page in range(1,550):

    # Define the URL of the Spitogatos search page
    url = f'https://www.spitogatos.gr/en/for_sale-homes/map-search/order_datemodified_desc/' + \
        f'page_{str(page)}?latitudeLow=34.849875&latitudeHigh=41.319076&longitudeLow=19.500732&longitudeHigh=30.52002&zoom=7'

    # Send a GET request to the URL
    response = requests.get(url, headers=headers)
    print(url)
    # print(response.status_code)
    soup = BeautifulSoup(response.content, 'html.parser')
    # Find all listings
    listings = soup.find_all('article', class_='ordered-element')
    # print(len(listings))
    if response.status_code != 200 or len(listings) == 0:
        print('Error', response.status_code)
        break

    for listing in listings:
        title = listing.find('h3', class_='tile__title').get_text(strip=True)
        price = listing.find('p', class_='price__text').get_text(strip=True)
        location = listing.find('h3', class_='tile__location').get_text(strip=True)
        details = listing.find('ul', class_='tile__info').get_text(strip=True) if listing.find('ul', class_='tile__info') else None
        url = listing.find('a')['href']
        image = listing.find('img')['src'] if listing.find('img') else None

        data.append({
            'title': title,
            'price_raw': price,
            'location': location,
            'details': details,
            'url': 'https://www.spitogatos.gr' + url,
            'image': image
        })

# Create a DataFrame from the data
df = pd.DataFrame(data)

if not df.empty:
    #Cleaning the data
    df["area"] = df.title.apply(lambda x: x.split(',')[-1].replace("m²", "").strip()).astype(int)
    df["estate_type"] = df.title.str.split(",").str[0].str.strip()
    df["price"] = df.price_raw.apply(lambda x: int(x.split('€')[1].replace(',', '').strip())) 
    df["price_per_m2"] = df.price / df.area
    df["price_per_m2"] = df["price_per_m2"].round(0)

df

https://www.spitogatos.gr/en/for_sale-homes/map-search/order_datemodified_desc/page_1?latitudeLow=34.849875&latitudeHigh=41.319076&longitudeLow=19.500732&longitudeHigh=30.52002&zoom=7
Error 200

Empty DataFrame
Columns: []
Index: []

In [8]:
import requests
from bs4 import BeautifulSoup

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
'Accept-Language': 'en-US,en;q=0.9',
'Accept-Encoding': 'gzip'}

data = []


base_url = f"https://www.immowelt.de/classified-search?distributionTypes=Rent&estateTypes=Apartment&locations=NBH2DE91297243&order=DateDesc&m=homepage_relunch_my_last_search_classified_search_result"

response = requests.get(base_url, headers=headers)
if response.status_code != 200:
    print('Error', response.status_code)
soup = BeautifulSoup(response.content, 'html.parser')
soup

<!DOCTYPE html>

<html lang="de">
<head>
<meta charset="utf-8"/>
<meta content="initial-scale=1, width=device-width" name="viewport"/>
<meta content="4.4.0" name="version:shell"/>
<meta content="live" name="deployment:environment"/>
<title data-rh="true">Wohnungen zur Miete in Oberbilk</title>
<meta content="" data-rh="true" name="description"><meta content="noindex, nofollow" data-rh="true" name="robots">
<script data-rh="true" defer="true" src="/shared/cardHandler.js" type="text/javascript"></script><script async="true" data-rh="true" src="https://dd.immowelt.de/tags.js" type="text/javascript"></script>
<link as="script" href="/assets/shell/main.22723e82.js" rel="preload"/>
<script defer="" src="/assets/shell/main.22723e82.js"></script>
<link as="script" href="https://www.immowelt.de/assets/apps/serp/v2/client/remoteEntry.js" rel="preload"/>
<script defer="" onerror="document.head.querySelector('script[src=\'https://www.immowelt.de/assets/apps/serp/v2/client/remoteEntry.js\']')?.setAttribute('data-error', 'true');" src="https://www.immowelt.de/assets/apps/serp/v2/client/remoteEntry.js"></script>

In [3]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

headers = {
    "authority": "www.redfin.com",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "accept-encoding": "gzip, deflate, br, zstd",
    "accept-language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,tr;q=0.6,hu;q=0.5",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "priority": "u=0, i",
    "referer": "https://www.redfin.com/",
    "sec-ch-ua": '"Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"',
    "sec-ch-ua-mobile": "?1",
    "sec-ch-ua-platform": '"Android"',
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "same-origin",
    "sec-fetch-user": "?1",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Mobile Safari/537.36",
}

url = 'https://www.redfin.com/city/17150/UT/Salt-Lake-City/filter/sort=lo-days'
r = requests.get(url, headers=headers)
soup = BeautifulSoup(r.content, 'lxml')

In [69]:
ads = soup.find_all('div', class_='bp-mobileListHomeCard')
final_ads = []

def safe_text(el, default=None):
    return el.get_text(strip=True) if el else default

def safe_attr(el, attr, default=None):
    return el.get(attr) if el and el.has_attr(attr) else default

for ad in ads:
    img = safe_attr(ad.find('img'), 'src')
    price = safe_text(ad.find('div', class_='bp-Homecard__Price'))
    bedrooms = safe_text(ad.find('span', class_='bp-Homecard__Stats--beds'))
    bathrooms = safe_text(ad.find('span', class_='bp-Homecard__Stats--baths'))
    area = safe_text(ad.find('span', class_='bp-Homecard__Stats--sqft'))
    address = safe_text(ad.find('a'))
    relative_url = safe_attr(ad.find('a'), 'href')
    final_ads.append({'img': img, 'price': price, 'bedrooms': bedrooms,
                      'bathrooms': bathrooms, 'area': area, 'address': address,
                      'relative_url': relative_url})

df = pd.DataFrame(final_ads)
df = df.dropna(how='all').reset_index(drop=True)
df

,img,price,bedrooms,bathrooms,area,address,relative_url
0,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$408,720",— beds,— baths,—sq ft,"Tract 2 E 500th Rd, Cherkee Hmstd, MO 65613",/MO/CHERKEE-HMSTD/Tract-2-E-500th-Rd-65613/hom...
1,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$750,000",4 beds,3 baths,"6,635sq ft","4978 S 11th Rd, Aldrich, MO 65601",/MO/Aldrich/4978-S-11th-Rd-65601/home/196038212
2,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$599,900",— beds,— baths,—sq ft,"006 County Road 14, North Morgan Township, MO ...",/MO/North-Morgan-Township/006-County-Road-14-6...
3,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$319,000",2 beds,2 baths,"1,230sq ft","805 E Dade 52, Dadeville, MO 65635",/MO/Dadeville/805-E-Dade-52-65635/home/185794944
4,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$2,700,000",3 beds,2.5 baths,"2,268sq ft","775 E 505th Rd, Aldrich, MO 65601",/MO/Aldrich/775-E-5o5-Th-Rd-65601/home/77786311
5,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$204,400",— beds,— baths,—sq ft,"Tract 3 E 500th Rd, Aldrich, MO 65601",/MO/Aldrich/3-E-500th-Rd-65601/home/201390591
6,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$99,000",— beds,— baths,—sq ft,"Tract 1 E 500th Rd, Bolivar, MO 65613",/MO/Bolivar/Tract-1-E-500th-RD-65613/home/2013...
7,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$1,100,000",— beds,— baths,—sq ft,"000 E 500th Rd, Cherkee Hmstd, MO 65613",/MO/CHERKEE-HMSTD/E-500th-Rd-65613/home/200256600
8,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$445,000",5 beds,3 baths,"3,566sq ft","936 E 482nd Rd, Bolivar, MO 65613",/MO/Bolivar/936-E-482nd-Rd-65613/home/77781746
9,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$300,000",— beds,— baths,—sq ft,"000 E 482nd Rd, Bolivar, MO 65613",/MO/Bolivar/E-482nd-Rd-Unknown/home/200002665
10,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$375,000",3 beds,2 baths,"1,568sq ft","940 E 482nd Rd, Bolivar, MO 65613",/MO/Bolivar/940-E-482nd-Rd-65613/home/199995274
11,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$359,000",2 beds,2 baths,"2,146sq ft","810 Missouri 215, Morrisville, MO 65710",/MO/Morrisville/810-Highway-215-65710/home/777...
12,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$210,000",1 bed,1 bath,832sq ft,"21515 S 215 Hwy, Dadeville, MO 65635",/MO/Dadeville/21515-S-Highway-215-65635/home/1...
13,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$114,900",2 beds,1 bath,"1,050sq ft","238 S Clompton St, Dadeville, MO 65635",/MO/Dadeville/238-S-Clompton-St-65635/home/779...
14,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$149,000",2 beds,2 baths,"1,216sq ft","675 N Dade 181, Greenfield, MO 65661",/MO/Greenfield/675-N-Dade-181-65661/home/77999006
15,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$250,000",— beds,— baths,—sq ft,"0 535, Morrisville, MO 65710",/MO/Morrisville/535-65710/home/197016329
16,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$90,000",3 beds,2 baths,"1,216sq ft","4662 S 30th Rd, Fair Play, MO 65649",/MO/Fair-Play/4662-S-30th-Rd-65649/home/77785672
17,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$999,900",1 bed,1 bath,504sq ft,"4775 S 50th Rd Rd, Aldrich, MO 65601",/MO/Aldrich/4775-S-50th-St-65601/home/194568059
18,https://ssl.cdn-redfin.com/photo/349/islphoto/...,"$3,550,000",6 beds,5.5 baths,"5,987sq ft","352 State Highway 245, Dadeville, MO 65635",/MO/Dadeville/352-State-Highway-245-65635/home...

In [ ]:
def clean(df_in : pd.DataFrame) -> pd.DataFrame:
    df = df_in.copy()
    df = df[~df.price.str.contains("Unknown")]
    df.loc[df.area.str.contains('—', na=False), 'area'] = None
    df.loc[df.bedrooms.str.contains('—', na=False), 'bedrooms'] = None
    df.loc[df.bathrooms.str.contains('—', na=False), 'bathrooms'] = None
    df["price"] = df.price.apply(lambda x: int(x.replace('$', '').replace(',', '').strip()) if x else None)
    df["bedrooms"] = df.bedrooms.apply(lambda x: int(x.split()[0]) if x else None)
    df["bathrooms"] = df.bathrooms.apply(lambda x: float(x.split()[0]) if x else None)
    df["unit"] = df.area.apply(lambda x: 'sq ft' if x and 'sq ft' in x else 'acre')
    df["area"] = df["area"].apply(lambda x: float(x.replace('sq ft', '').replace('acres (lot)', '') \
                                                .replace(',', '').strip()) if x else None)
    df["url"] = "https://www.redfin.com" + df["relative_url"]
    df["area_m2"] = df.apply(lambda row: round(row.area * 0.092903, 2) if row.unit == 'sq ft' else round(row.area * 4046.86, 2) if row.unit == 'acre' else None, axis=1)
    df["price_per_m2"] = df.apply(lambda row: round(row.price / row.area_m2, 2) if row.price and row.area_m2 else None, axis=1)
    df["source"] = "redfin"
    df["query_date"] = pd.Timestamp.now().date()

    return df

clean(df).sort_values(by='price_per_m2')

In [110]:
df.area.apply(lambda x: 'sq ft' if x and 'sq ft' in x else 'acre').unique()

array(['sq ft', 'acre'], dtype=object)

In [5]:
us_data = {
    "Alabama": {"code": "AL", "counties": {
        "Autauga County": 119, "Baldwin County": 120, "Barbour County": 121, "Bibb County": 122,
        "Blount County": 123, "Bullock County": 124, "Butler County": 125, "Calhoun County": 126,
        "Chambers County": 127, "Cherokee County": 128, "Chilton County": 129, "Choctaw County": 130,
        "Clarke County": 131, "Clay County": 132, "Cleburne County": 133, "Coffee County": 134,
        "Colbert County": 135, "Conecuh County": 136, "Coosa County": 137, "Covington County": 138,
        "Crenshaw County": 139, "Cullman County": 140, "Dale County": 141, "Dallas County": 142,
        "DeKalb County": 143, "Elmore County": 144, "Escambia County": 145, "Etowah County": 146,
        "Fayette County": 147, "Franklin County": 148, "Geneva County": 149, "Greene County": 150,
        "Hale County": 151, "Henry County": 152, "Houston County": 153, "Jackson County": 154,
        "Jefferson County": 155, "Lamar County": 156, "Lauderdale County": 157, "Lawrence County": 158,
        "Lee County": 159, "Limestone County": 160, "Lowndes County": 161, "Macon County": 162,
        "Madison County": 163, "Marengo County": 164, "Marion County": 165, "Marshall County": 166,
        "Mobile County": 167, "Monroe County": 168, "Montgomery County": 169, "Morgan County": 170,
        "Perry County": 171, "Pickens County": 172, "Pike County": 173, "Randolph County": 174,
        "Russell County": 175, "Shelby County": 177, "St. Clair County": 176, "Sumter County": 178,
        "Talladega County": 179, "Tallapoosa County": 180, "Tuscaloosa County": 181, "Walker County": 182,
        "Washington County": 183, "Wilcox County": 184, "Winston County": 185,
    }},
    "Alaska": {"code": "AK", "counties": {
    "Aleutians East Borough": 186, "Aleutians West Census Area": 187, "Anchorage Borough": 188,
    "Bethel Census Area": 189, "Bristol Bay Borough": 190, "Denali Borough": 191,
    "Dillingham Census Area": 192, "Fairbanks North Star Borough": 193, "Haines Borough": 194,
    "Hoonah Angoon Census Area": 3351, "Juneau Borough": 195, "Kenai Peninsula Borough": 196,
    "Ketchikan Gateway Borough": 197, "Kodiak Island Borough": 198, "Kusilvak Census Area": 209,
    "Lake and Peninsula Borough": 199, "Matanuska Susitna Borough": 200, "Nome Census Area": 201,
    "North Slope Borough": 202, "Northwest Arctic Borough": 203, "Petersburg Borough": 3352,
    "Prince of Wales Hyder Census Area": 204, "Sitka Borough": 205, "Skagway Borough": 206,
    "Southeast Fairbanks Census Area": 207, "Valdez Cordova Census Area": 208,
    "Wrangell Borough": 210, "Yakutat Borough": 211, "Yukon Koyukuk Census Area": 212,
    }},
    "Arizona": {"code": "AZ", "counties": {
        "Apache County": 213, "Cochise County": 214, "Coconino County": 215, "Gila County": 216,
        "Graham County": 217, "Greenlee County": 218, "La Paz County": 219, "Maricopa County": 220,
        "Mohave County": 221, "Navajo County": 222, "Pima County": 223, "Pinal County": 224,
        "Santa Cruz County": 225, "Yavapai County": 226, "Yuma County": 227,
    }},
    "Arkansas": {"code": "AR", "counties": {
        "Arkansas County": 228, "Ashley County": 229, "Baxter County": 230, "Benton County": 231,
        "Boone County": 232, "Bradley County": 233, "Calhoun County": 234, "Carroll County": 235,
        "Chicot County": 236, "Clark County": 237, "Clay County": 238, "Cleburne County": 239,
        "Cleveland County": 240, "Columbia County": 241, "Conway County": 242, "Craighead County": 243,
        "Crawford County": 244, "Crittenden County": 245, "Cross County": 246, "Dallas County": 247,
        "Desha County": 248, "Drew County": 249, "Faulkner County": 250, "Franklin County": 251,
        "Fulton County": 252, "Garland County": 253, "Grant County": 254, "Greene County": 255,
        "Hempstead County": 256, "Hot Spring County": 257, "Howard County": 258, "Independence County": 259,
        "Izard County": 260, "Jackson County": 261, "Jefferson County": 262, "Johnson County": 263,
        "Lafayette County": 264, "Lawrence County": 265, "Lee County": 266, "Lincoln County": 267,
        "Little River County": 268, "Logan County": 269, "Lonoke County": 270, "Madison County": 271,
        "Marion County": 272, "Miller County": 273, "Mississippi County": 274, "Monroe County": 275,
        "Montgomery County": 276, "Nevada County": 277, "Newton County": 278, "Ouachita County": 279,
        "Perry County": 280, "Phillips County": 281, "Pike County": 282, "Poinsett County": 283,
        "Polk County": 284, "Pope County": 285, "Prairie County": 286, "Pulaski County": 287,
        "Randolph County": 288, "Saline County": 290, "Scott County": 291, "Searcy County": 292,
        "Sebastian County": 293, "Sevier County": 294, "Sharp County": 295, "St. Francis County": 289,
        "Stone County": 296, "Union County": 297, "Van Buren County": 298, "Washington County": 299,
        "White County": 300, "Woodruff County": 301, "Yell County": 302,
    }},
    "California": {"code": "CA", "counties": {
        "Alameda County": 303, "Alpine County": 304, "Amador County": 305, "Butte County": 306,
        "Calaveras County": 307, "Colusa County": 308, "Contra Costa County": 309, "Del Norte County": 310,
        "El Dorado County": 311, "Fresno County": 312, "Glenn County": 313, "Humboldt County": 314,
        "Imperial County": 315, "Inyo County": 316, "Kern County": 317, "Kings County": 318,
        "Lake County": 319, "Lassen County": 320, "Los Angeles County": 321, "Madera County": 322,
        "Marin County": 323, "Mariposa County": 324, "Mendocino County": 325, "Merced County": 326,
        "Modoc County": 327, "Mono County": 328, "Monterey County": 329, "Napa County": 330,
        "Nevada County": 331, "Orange County": 332, "Placer County": 333, "Plumas County": 334,
        "Riverside County": 335, "Sacramento County": 336, "San Benito County": 337, "San Bernardino County": 338,
        "San Diego County": 339, "San Francisco County": 340, "San Joaquin County": 341, "San Luis Obispo County": 342,
        "San Mateo County": 343, "Santa Barbara County": 344, "Santa Clara County": 345, "Santa Cruz County": 346,
        "Shasta County": 347, "Sierra County": 348, "Siskiyou County": 349, "Solano County": 350,
        "Sonoma County": 351, "Stanislaus County": 352, "Sutter County": 353, "Tehama County": 354,
        "Trinity County": 355, "Tulare County": 356, "Tuolumne County": 357, "Ventura County": 358,
        "Yolo County": 359, "Yuba County": 360,
    }},
    "Colorado": {"code": "CO", "counties": {
        "Adams County": 361, "Alamosa County": 362, "Arapahoe County": 363, "Archuleta County": 364,
        "Baca County": 365, "Bent County": 366, "Boulder County": 367, "Broomfield County": 368,
        "Chaffee County": 369, "Cheyenne County": 370, "Clear Creek County": 371, "Conejos County": 372,
        "Costilla County": 373, "Crowley County": 374, "Custer County": 375, "Delta County": 376,
        "Denver County": 377, "Dolores County": 378, "Douglas County": 379, "Eagle County": 380,
        "El Paso County": 382, "Elbert County": 381, "Fremont County": 383, "Garfield County": 384,
        "Gilpin County": 385, "Grand County": 386, "Gunnison County": 387, "Hinsdale County": 388,
        "Huerfano County": 389, "Jackson County": 390, "Jefferson County": 391, "Kiowa County": 392,
        "Kit Carson County": 393, "La Plata County": 395, "Lake County": 394, "Larimer County": 396,
        "Las Animas County": 397, "Lincoln County": 398, "Logan County": 399, "Mesa County": 400,
        "Mineral County": 401, "Moffat County": 402, "Montezuma County": 403, "Montrose County": 404,
        "Morgan County": 405, "Otero County": 406, "Ouray County": 407, "Park County": 408,
        "Phillips County": 409, "Pitkin County": 410, "Prowers County": 411, "Pueblo County": 412,
        "Rio Blanco County": 413, "Rio Grande County": 414, "Routt County": 415, "Saguache County": 416,
        "San Juan County": 417, "San Miguel County": 418, "Sedgwick County": 419, "Summit County": 420,
        "Teller County": 421, "Washington County": 422, "Weld County": 423, "Yuma County": 424,
    }},
    "Columbia": {"code": "DC", "counties": {"District of Columbia": 436}},
    "Connecticut": {"code": "CT", "counties": {
        "Fairfield County": 425, "Hartford County": 426, "Litchfield County": 427, "Middlesex County": 428,
        "New Haven County": 429, "New London County": 430, "Tolland County": 431, "Windham County": 432,
    }},
    "Delaware": {"code": "DE", "counties": {}},
    "Florida": {"code": "FL", "counties": {
        "Alachua County": 437, "Baker County": 438, "Bay County": 439, "Bradford County": 440,
        "Brevard County": 441, "Broward County": 442, "Calhoun County": 443, "Charlotte County": 444,
        "Citrus County": 445, "Clay County": 446, "Collier County": 447, "Columbia County": 448,
        "DeSoto County": 449, "Dixie County": 450, "Duval County": 451, "Escambia County": 452,
        "Flagler County": 453, "Franklin County": 454, "Gadsden County": 455, "Gilchrist County": 456,
        "Glades County": 457, "Gulf County": 458, "Hamilton County": 459, "Hardee County": 460,
        "Hendry County": 461, "Hernando County": 462, "Highlands County": 463, "Hillsborough County": 464,
        "Holmes County": 465, "Indian River County": 466, "Jackson County": 467, "Jefferson County": 468,
        "Lafayette County": 469, "Lake County": 470, "Lee County": 471, "Leon County": 472,
        "Levy County": 473, "Liberty County": 474, "Madison County": 475, "Manatee County": 476,
        "Marion County": 477, "Martin County": 478, "Miami Dade County": 479, "Monroe County": 480,
        "Nassau County": 481, "Okaloosa County": 482, "Okeechobee County": 483, "Orange County": 484,
        "Osceola County": 485, "Palm Beach County": 486, "Pasco County": 487, "Pinellas County": 488,
        "Polk County": 489, "Putnam County": 490, "Santa Rosa County": 493, "Sarasota County": 494,
        "Seminole County": 495, "St. Johns County": 491, "St. Lucie County": 492, "Sumter County": 496,
        "Suwannee County": 497, "Taylor County": 498, "Union County": 499, "Volusia County": 500,
        "Wakulla County": 501, "Walton County": 502, "Washington County": 503,
    }},
    "Georgia": {"code": "GA", "counties": {
        "Appling County": 504, "Atkinson County": 505, "Bacon County": 506, "Baker County": 507,
        "Baldwin County": 508, "Banks County": 509, "Barrow County": 510, "Bartow County": 511,
        "Ben Hill County": 512, "Berrien County": 513, "Bibb County": 514, "Bleckley County": 515,
        "Brantley County": 516, "Brooks County": 517, "Bryan County": 518, "Bulloch County": 519,
        "Burke County": 520, "Butts County": 521, "Calhoun County": 522, "Camden County": 523,
        "Candler County": 524, "Carroll County": 525, "Catoosa County": 526, "Charlton County": 527,
        "Chatham County": 528, "Chattahoochee County": 529, "Chattooga County": 530, "Cherokee County": 531,
        "Clarke County": 532, "Clay County": 533, "Clayton County": 534, "Clinch County": 535,
        "Cobb County": 536, "Coffee County": 537, "Colquitt County": 538, "Columbia County": 539,
        "Cook County": 540, "Coweta County": 541, "Crawford County": 542, "Crisp County": 543,
        "Dade County": 544, "Dawson County": 545, "Decatur County": 546, "DeKalb County": 547,
        "Dodge County": 548, "Dooly County": 549, "Dougherty County": 550, "Douglas County": 551,
        "Early County": 552, "Echols County": 553, "Effingham County": 554, "Elbert County": 555,
        "Emanuel County": 556, "Evans County": 557, "Fannin County": 558, "Fayette County": 559,
        "Floyd County": 560, "Forsyth County": 561, "Franklin County": 562, "Fulton County": 563,
        "Gilmer County": 564, "Glascock County": 565, "Glynn County": 566, "Gordon County": 567,
        "Grady County": 568, "Greene County": 569, "Gwinnett County": 570, "Habersham County": 571,
        "Hall County": 572, "Hancock County": 573, "Haralson County": 574, "Harris County": 575,
        "Hart County": 576, "Heard County": 577, "Henry County": 578, "Houston County": 579,
        "Irwin County": 580, "Jackson County": 581, "Jasper County": 582, "Jeff Davis County": 583,
        "Jefferson County": 584, "Jenkins County": 585, "Johnson County": 586, "Jones County": 587,
        "Lamar County": 588, "Lanier County": 589, "Laurens County": 590, "Lee County": 591,
        "Liberty County": 592, "Lincoln County": 593, "Long County": 594, "Lowndes County": 595,
        "Lumpkin County": 596, "Macon County": 599, "Madison County": 600, "Marion County": 601,
        "McDuffie County": 597, "McIntosh County": 598, "Meriwether County": 602, "Miller County": 603,
        "Mitchell County": 604, "Monroe County": 605, "Montgomery County": 606, "Morgan County": 607,
        "Murray County": 608, "Muscogee County": 609, "Newton County": 610, "Oconee County": 611,
        "Oglethorpe County": 612, "Paulding County": 613, "Peach County": 614, "Pickens County": 615,
        "Pierce County": 616, "Pike County": 617, "Polk County": 618, "Pulaski County": 619,
        "Putnam County": 620, "Quitman County": 621, "Rabun County": 622, "Randolph County": 623,
        "Richmond County": 624, "Rockdale County": 625, "Schley County": 626, "Screven County": 627,
        "Seminole County": 628, "Spalding County": 629, "Stephens County": 630, "Stewart County": 631,
        "Sumter County": 632, "Talbot County": 633, "Taliaferro County": 634, "Tattnall County": 635,
        "Taylor County": 636, "Telfair County": 637, "Terrell County": 638, "Thomas County": 639,
        "Tift County": 640, "Toombs County": 641, "Towns County": 642, "Treutlen County": 643,
        "Troup County": 644, "Turner County": 645, "Twiggs County": 646, "Union County": 647,
        "Upson County": 648, "Walker County": 649, "Walton County": 650, "Ware County": 651,
        "Warren County": 652, "Washington County": 653, "Wayne County": 654, "Webster County": 655,
        "Wheeler County": 656, "White County": 657, "Whitfield County": 658, "Wilcox County": 659,
        "Wilkes County": 660, "Wilkinson County": 661, "Worth County": 662,
    }},
    "Hawaii": {"code": "HI", "counties": {
        "Hawaii County": 663, "Honolulu County": 664, "Kalawao County": 665,
        "Kauai County": 666, "Maui County": 667,
    }},
    "Idaho": {"code": "ID", "counties": {}},
    "Illinois": {"code": "IL", "counties": {
        "Adams County": 712, "Alexander County": 713, "Bond County": 714, "Boone County": 715,
        "Brown County": 716, "Bureau County": 717, "Calhoun County": 718, "Carroll County": 719,
        "Cass County": 720, "Champaign County": 721, "Christian County": 722, "Clark County": 723,
        "Clay County": 724, "Clinton County": 725, "Coles County": 726, "Cook County": 727,
        "Crawford County": 728, "Cumberland County": 729, "De Witt County": 731, "DeKalb County": 730,
        "Douglas County": 732, "DuPage County": 733, "Edgar County": 734, "Edwards County": 735,
        "Effingham County": 736, "Fayette County": 737, "Ford County": 738, "Franklin County": 739,
        "Fulton County": 740, "Gallatin County": 741, "Greene County": 742, "Grundy County": 743,
        "Hamilton County": 744, "Hancock County": 745, "Hardin County": 746, "Henderson County": 747,
        "Henry County": 748, "Iroquois County": 749, "Jackson County": 750, "Jasper County": 751,
        "Jefferson County": 752, "Jersey County": 753, "Jo Daviess County": 754, "Johnson County": 755,
        "Kane County": 756, "Kankakee County": 757, "Kendall County": 758, "Knox County": 759,
        "Lake County": 760, "LaSalle County": 761, "Lawrence County": 762, "Lee County": 763,
        "Livingston County": 764, "Logan County": 765, "Macon County": 769, "Macoupin County": 770,
        "Madison County": 771, "Marion County": 772, "Marshall County": 773, "Mason County": 774,
        "Massac County": 775, "McDonough County": 766, "McHenry County": 767, "McLean County": 768,
        "Menard County": 776, "Mercer County": 777, "Monroe County": 778, "Montgomery County": 779,
        "Morgan County": 780, "Moultrie County": 781, "Ogle County": 782, "Peoria County": 783,
        "Perry County": 784, "Piatt County": 785, "Pike County": 786, "Pope County": 787,
        "Pulaski County": 788, "Putnam County": 789, "Randolph County": 790, "Richland County": 791,
        "Rock Island County": 792, "Saline County": 794, "Sangamon County": 795, "Schuyler County": 796,
        "Scott County": 797, "Shelby County": 798, "St. Clair County": 793, "Stark County": 799,
        "Stephenson County": 800, "Tazewell County": 801, "Union County": 802, "Vermilion County": 803,
        "Wabash County": 804, "Warren County": 805, "Washington County": 806, "Wayne County": 807,
        "White County": 808, "Whiteside County": 809, "Will County": 810, "Williamson County": 811,
        "Winnebago County": 812, "Woodford County": 813,
    }},
    "Indiana": {"code": "IN", "counties": {
        "Adams County": 814, "Allen County": 815, "Bartholomew County": 816, "Benton County": 817,
        "Blackford County": 818, "Boone County": 819, "Brown County": 820, "Carroll County": 821,
        "Cass County": 822, "Clark County": 823, "Clay County": 824, "Clinton County": 825,
        "Crawford County": 826, "Daviess County": 827, "Dearborn County": 828, "Decatur County": 829,
        "DeKalb County": 830, "Delaware County": 831, "Dubois County": 832, "Elkhart County": 833,
        "Fayette County": 834, "Floyd County": 835, "Fountain County": 836, "Franklin County": 837,
        "Fulton County": 838, "Gibson County": 839, "Grant County": 840, "Greene County": 841,
        "Hamilton County": 842, "Hancock County": 843, "Harrison County": 844, "Hendricks County": 845,
        "Henry County": 846, "Howard County": 847, "Huntington County": 848, "Jackson County": 849,
        "Jasper County": 850, "Jay County": 851, "Jefferson County": 852, "Jennings County": 853,
        "Johnson County": 854, "Knox County": 855, "Kosciusko County": 856, "LaGrange County": 857,
        "Lake County": 858, "LaPorte County": 859, "Lawrence County": 860, "Madison County": 861,
        "Marion County": 862, "Marshall County": 863, "Martin County": 864, "Miami County": 865,
        "Monroe County": 866, "Montgomery County": 867, "Morgan County": 868, "Newton County": 869,
        "Noble County": 870, "Ohio County": 871, "Orange County": 872, "Owen County": 873,
        "Parke County": 874, "Perry County": 875, "Pike County": 876, "Porter County": 877,
        "Posey County": 878, "Pulaski County": 879, "Putnam County": 880, "Randolph County": 881,
        "Ripley County": 882, "Rush County": 883, "Scott County": 885, "Shelby County": 886,
        "Spencer County": 887, "St. Joseph County": 884, "Starke County": 888, "Steuben County": 889,
        "Sullivan County": 890, "Switzerland County": 891, "Tippecanoe County": 892, "Tipton County": 893,
        "Union County": 894, "Vanderburgh County": 895, "Vermillion County": 896, "Vigo County": 897,
        "Wabash County": 898, "Warren County": 899, "Warrick County": 900, "Washington County": 901,
        "Wayne County": 902, "Wells County": 903, "White County": 904, "Whitley County": 905,
    }},
    "Iowa": {"code": "IA", "counties": {}},
    "Kansas": {"code": "KS", "counties": {}},
    "Kentucky": {"code": "KY", "counties": {}},
    "Louisiana": {"code": "LA", "counties": {}},
    "Maine": {"code": "ME", "counties": {}},
    "Maryland": {"code": "MD", "counties": {}},
    "Massachusetts": {"code": "MA", "counties": {
        "Barnstable County": 1334, "Berkshire County": 1335, "Bristol County": 1336, "Dukes County": 1337,
        "Essex County": 1338, "Franklin County": 1339, "Hampden County": 1340, "Hampshire County": 1341,
        "Middlesex County": 1342, "Nantucket County": 1343, "Norfolk County": 1344, "Plymouth County": 1345,
        "Suffolk County": 1346, "Worcester County": 1347,
    }},
    "Michigan": {"code": "MI", "counties": {
        "Alcona County": 1348, "Alger County": 1349, "Allegan County": 1350, "Alpena County": 1351,
        "Antrim County": 1352, "Arenac County": 1353, "Baraga County": 1354, "Barry County": 1355,
        "Bay County": 1356, "Benzie County": 1357, "Berrien County": 1358, "Branch County": 1359,
        "Calhoun County": 1360, "Cass County": 1361, "Charlevoix County": 1362, "Cheboygan County": 1363,
        "Chippewa County": 1364, "Clare County": 1365, "Clinton County": 1366, "Crawford County": 1367,
        "Delta County": 1368, "Dickinson County": 1369, "Eaton County": 1370, "Emmet County": 1371,
        "Genesee County": 1372, "Gladwin County": 1373, "Gogebic County": 1374, "Grand Traverse County": 1375,
        "Gratiot County": 1376, "Hillsdale County": 1377, "Houghton County": 1378, "Huron County": 1379,
        "Ingham County": 1380, "Ionia County": 1381, "Iosco County": 1382, "Iron County": 1383,
        "Isabella County": 1384, "Jackson County": 1385, "Kalamazoo County": 1386, "Kalkaska County": 1387,
        "Kent County": 1388, "Keweenaw County": 1389, "Lake County": 1390, "Lapeer County": 1391,
        "Leelanau County": 1392, "Lenawee County": 1393, "Livingston County": 1394, "Luce County": 1395,
        "Mackinac County": 1396, "Macomb County": 1397, "Manistee County": 1398, "Marquette County": 1399,
        "Mason County": 1400, "Mecosta County": 1401, "Menominee County": 1402, "Midland County": 1403,
        "Missaukee County": 1404, "Monroe County": 1405, "Montcalm County": 1406, "Montmorency County": 1407,
        "Muskegon County": 1408, "Newaygo County": 1409, "Oakland County": 1410, "Oceana County": 1411,
        "Ogemaw County": 1412, "Ontonagon County": 1413, "Osceola County": 1414, "Oscoda County": 1415,
        "Otsego County": 1416, "Ottawa County": 1417, "Presque Isle County": 1418, "Roscommon County": 1419,
        "Saginaw County": 1420, "Sanilac County": 1423, "Schoolcraft County": 1424, "Shiawassee County": 1425,
        "St. Clair County": 1421, "St. Joseph County": 1422, "Tuscola County": 1426, "Van Buren County": 1427,
        "Washtenaw County": 1428, "Wayne County": 1429, "Wexford County": 1430,
    }},
    "Minnesota": {"code": "MN", "counties": {}},
    "Mississippi": {"code": "MS", "counties": {}},
    "Missouri": {"code": "MO", "counties": {}},
    "Montana": {"code": "MT", "counties": {}},
    "Nebraska": {"code": "NE", "counties": {}},
    "Nevada": {"code": "NV", "counties": {}},
    "New Hampshire": {"code": "NH", "counties": {}},
    "New Jersey": {"code": "NJ", "counties": {
        "Atlantic County": 1891, "Bergen County": 1892, "Burlington County": 1893, "Camden County": 1894,
        "Cape May County": 1895, "Cumberland County": 1896, "Essex County": 1897, "Gloucester County": 1898,
        "Hudson County": 1899, "Hunterdon County": 1900, "Mercer County": 1901, "Middlesex County": 1902,
        "Monmouth County": 1903, "Morris County": 1904, "Ocean County": 1905, "Passaic County": 1906,
        "Salem County": 1907, "Somerset County": 1908, "Sussex County": 1909, "Union County": 1910,
        "Warren County": 1911,
    }},
    "New Mexico": {"code": "NM", "counties": {}},
    "New York": {"code": "NY", "counties": {
        "Albany County": 1945, "Allegany County": 1946, "Bronx County": 1947, "Broome County": 1948,
        "Cattaraugus County": 1949, "Cayuga County": 1950, "Chautauqua County": 1951, "Chemung County": 1952,
        "Chenango County": 1953, "Clinton County": 1954, "Columbia County": 1955, "Cortland County": 1956,
        "Delaware County": 1957, "Dutchess County": 1958, "Erie County": 1959, "Essex County": 1960,
        "Franklin County": 1961, "Fulton County": 1962, "Genesee County": 1963, "Greene County": 1964,
        "Hamilton County": 1965, "Herkimer County": 1966, "Jefferson County": 1967, "Kings County": 1968,
        "Lewis County": 1969, "Livingston County": 1970, "Madison County": 1971, "Monroe County": 1972,
        "Montgomery County": 1973, "Nassau County": 1974, "New York County": 1975, "Niagara County": 1976,
        "Oneida County": 1977, "Onondaga County": 1978, "Ontario County": 1979, "Orange County": 1980,
        "Orleans County": 1981, "Oswego County": 1982, "Otsego County": 1983, "Putnam County": 1984,
        "Queens County": 1985, "Rensselaer County": 1986, "Richmond County": 1987, "Rockland County": 1988,
        "Saratoga County": 1990, "Schenectady County": 1991, "Schoharie County": 1992, "Schuyler County": 1993,
        "Seneca County": 1994, "St. Lawrence County": 1989, "Steuben County": 1995, "Suffolk County": 1996,
        "Sullivan County": 1997, "Tioga County": 1998, "Tompkins County": 1999, "Ulster County": 2000,
        "Warren County": 2001, "Washington County": 2002, "Wayne County": 2003, "Westchester County": 2004,
        "Wyoming County": 2005, "Yates County": 2006,
    }},
    "North Carolina": {"code": "NC", "counties": {
        "Alamance County": 2007, "Alexander County": 2008, "Alleghany County": 2009, "Anson County": 2010,
        "Ashe County": 2011, "Avery County": 2012, "Beaufort County": 2013, "Bertie County": 2014,
        "Bladen County": 2015, "Brunswick County": 2016, "Buncombe County": 2017, "Burke County": 2018,
        "Cabarrus County": 2019, "Caldwell County": 2020, "Camden County": 2021, "Carteret County": 2022,
        "Caswell County": 2023, "Catawba County": 2024, "Chatham County": 2025, "Cherokee County": 2026,
        "Chowan County": 2027, "Clay County": 2028, "Cleveland County": 2029, "Columbus County": 2030,
        "Craven County": 2031, "Cumberland County": 2032, "Currituck County": 2033, "Dare County": 2034,
        "Davidson County": 2035, "Davie County": 2036, "Duplin County": 2037, "Durham County": 2038,
        "Edgecombe County": 2039, "Forsyth County": 2040, "Franklin County": 2041, "Gaston County": 2042,
        "Gates County": 2043, "Graham County": 2044, "Granville County": 2045, "Greene County": 2046,
        "Guilford County": 2047, "Halifax County": 2048, "Harnett County": 2049, "Haywood County": 2050,
        "Henderson County": 2051, "Hertford County": 2052, "Hoke County": 2053, "Hyde County": 2054,
        "Iredell County": 2055, "Jackson County": 2056, "Johnston County": 2057, "Jones County": 2058,
        "Lee County": 2059, "Lenoir County": 2060, "Lincoln County": 2061, "Macon County": 2063,
        "Madison County": 2064, "Martin County": 2065, "McDowell County": 2062, "Mecklenburg County": 2066,
        "Mitchell County": 2067, "Montgomery County": 2068, "Moore County": 2069, "Nash County": 2070,
        "New Hanover County": 2071, "Northampton County": 2072, "Onslow County": 2073, "Orange County": 2074,
        "Pamlico County": 2075, "Pasquotank County": 2076, "Pender County": 2077, "Perquimans County": 2078,
        "Person County": 2079, "Pitt County": 2080, "Polk County": 2081, "Randolph County": 2082,
        "Richmond County": 2083, "Robeson County": 2084, "Rockingham County": 2085, "Rowan County": 2086,
        "Rutherford County": 2087, "Sampson County": 2088, "Scotland County": 2089, "Stanly County": 2090,
        "Stokes County": 2091, "Surry County": 2092, "Swain County": 2093, "Transylvania County": 2094,
        "Tyrrell County": 2095, "Union County": 2096, "Vance County": 2097, "Wake County": 2098,
        "Warren County": 2099, "Washington County": 2100, "Watauga County": 2101, "Wayne County": 2102,
        "Wilkes County": 2103, "Wilson County": 2104, "Yadkin County": 2105, "Yancey County": 2106,
    }},
    "North Dakota": {"code": "ND", "counties": {}},
    "Ohio": {"code": "OH", "counties": {
        "Adams County": 2160, "Allen County": 2161, "Ashland County": 2162, "Ashtabula County": 2163,
        "Athens County": 2164, "Auglaize County": 2165, "Belmont County": 2166, "Brown County": 2167,
        "Butler County": 2168, "Carroll County": 2169, "Champaign County": 2170, "Clark County": 2171,
        "Clermont County": 2172, "Clinton County": 2173, "Columbiana County": 2174, "Coshocton County": 2175,
        "Crawford County": 2176, "Cuyahoga County": 2177, "Darke County": 2178, "Defiance County": 2179,
        "Delaware County": 2180, "Erie County": 2181, "Fairfield County": 2182, "Fayette County": 2183,
        "Franklin County": 2184, "Fulton County": 2185, "Gallia County": 2186, "Geauga County": 2187,
        "Greene County": 2188, "Guernsey County": 2189, "Hamilton County": 2190, "Hancock County": 2191,
        "Hardin County": 2192, "Harrison County": 2193, "Henry County": 2194, "Highland County": 2195,
        "Hocking County": 2196, "Holmes County": 2197, "Huron County": 2198, "Jackson County": 2199,
        "Jefferson County": 2200, "Knox County": 2201, "Lake County": 2202, "Lawrence County": 2203,
        "Licking County": 2204, "Logan County": 2205, "Lorain County": 2206, "Lucas County": 2207,
        "Madison County": 2208, "Mahoning County": 2209, "Marion County": 2210, "Medina County": 2211,
        "Meigs County": 2212, "Mercer County": 2213, "Miami County": 2214, "Monroe County": 2215,
        "Montgomery County": 2216, "Morgan County": 2217, "Morrow County": 2218, "Muskingum County": 2219,
        "Noble County": 2220, "Ottawa County": 2221, "Paulding County": 2222, "Perry County": 2223,
        "Pickaway County": 2224, "Pike County": 2225, "Portage County": 2226, "Preble County": 2227,
        "Putnam County": 2228, "Richland County": 2229, "Ross County": 2230, "Sandusky County": 2231,
        "Scioto County": 2232, "Seneca County": 2233, "Shelby County": 2234, "Stark County": 2235,
        "Summit County": 2236, "Trumbull County": 2237, "Tuscarawas County": 2238, "Union County": 2239,
        "Van Wert County": 2240, "Vinton County": 2241, "Warren County": 2242, "Washington County": 2243,
        "Wayne County": 2244, "Williams County": 2245, "Wood County": 2246, "Wyandot County": 2247,
    }},
    "Oklahoma": {"code": "OK", "counties": {}},
    "Oregon": {"code": "OR", "counties": {}},
    "Pennsylvania": {"code": "PA", "counties": {
        "Adams County": 2361, "Allegheny County": 2362, "Armstrong County": 2363, "Beaver County": 2364,
        "Bedford County": 2365, "Berks County": 2366, "Blair County": 2367, "Bradford County": 2368,
        "Bucks County": 2369, "Butler County": 2370, "Cambria County": 2371, "Cameron County": 2372,
        "Carbon County": 2373, "Centre County": 2374, "Chester County": 2375, "Clarion County": 2376,
        "Clearfield County": 2377, "Clinton County": 2378, "Columbia County": 2379, "Crawford County": 2380,
        "Cumberland County": 2381, "Dauphin County": 2382, "Delaware County": 2383, "Elk County": 2384,
        "Erie County": 2385, "Fayette County": 2386, "Forest County": 2387, "Franklin County": 2388,
        "Fulton County": 2389, "Greene County": 2390, "Huntingdon County": 2391, "Indiana County": 2392,
        "Jefferson County": 2393, "Juniata County": 2394, "Lackawanna County": 2395, "Lancaster County": 2396,
        "Lawrence County": 2397, "Lebanon County": 2398, "Lehigh County": 2399, "Luzerne County": 2400,
        "Lycoming County": 2401, "McKean County": 2402, "Mercer County": 2403, "Mifflin County": 2404,
        "Monroe County": 2405, "Montgomery County": 2406, "Montour County": 2407, "Northampton County": 2408,
        "Northumberland County": 2409, "Perry County": 2410, "Philadelphia County": 2411, "Pike County": 2412,
        "Potter County": 2413, "Schuylkill County": 2414, "Snyder County": 2415, "Somerset County": 2416,
        "Sullivan County": 2417, "Susquehanna County": 2418, "Tioga County": 2419, "Union County": 2420,
        "Venango County": 2421, "Warren County": 2422, "Washington County": 2423, "Wayne County": 2424,
        "Westmoreland County": 2425, "Wyoming County": 2426, "York County": 2427,
    }},
    "Rhode Island": {"code": "RI", "counties": {}},
    "South Carolina": {"code": "SC", "counties": {}},
    "South Dakota": {"code": "SD", "counties": {}},
    "Tennessee": {"code": "TN", "counties": {
        "Anderson County": 2545, "Bedford County": 2546, "Benton County": 2547, "Bledsoe County": 2548,
        "Blount County": 2549, "Bradley County": 2550, "Campbell County": 2551, "Cannon County": 2552,
        "Carroll County": 2553, "Carter County": 2554, "Cheatham County": 2555, "Chester County": 2556,
        "Claiborne County": 2557, "Clay County": 2558, "Cocke County": 2559, "Coffee County": 2560,
        "Crockett County": 2561, "Cumberland County": 2562, "Davidson County": 2563, "Decatur County": 2564,
        "DeKalb County": 2565, "Dickson County": 2566, "Dyer County": 2567, "Fayette County": 2568,
        "Fentress County": 2569, "Franklin County": 2570, "Gibson County": 2571, "Giles County": 2572,
        "Grainger County": 2573, "Greene County": 2574, "Grundy County": 2575, "Hamblen County": 2576,
        "Hamilton County": 2577, "Hancock County": 2578, "Hardeman County": 2579, "Hardin County": 2580,
        "Hawkins County": 2581, "Haywood County": 2582, "Henderson County": 2583, "Henry County": 2584,
        "Hickman County": 2585, "Houston County": 2586, "Humphreys County": 2587, "Jackson County": 2588,
        "Jefferson County": 2589, "Johnson County": 2590, "Knox County": 2591, "Lake County": 2592,
        "Lauderdale County": 2593, "Lawrence County": 2594, "Lewis County": 2595, "Lincoln County": 2596,
        "Loudon County": 2597, "Macon County": 2600, "Madison County": 2601, "Marion County": 2602,
        "Marshall County": 2603, "Maury County": 2604, "McMinn County": 2598, "McNairy County": 2599,
        "Meigs County": 2605, "Monroe County": 2606, "Montgomery County": 2607, "Moore County": 2608,
        "Morgan County": 2609, "Obion County": 2610, "Overton County": 2611, "Perry County": 2612,
        "Pickett County": 2613, "Polk County": 2614, "Putnam County": 2615, "Rhea County": 2616,
        "Roane County": 2617, "Robertson County": 2618, "Rutherford County": 2619, "Scott County": 2620,
        "Sequatchie County": 2621, "Sevier County": 2622, "Shelby County": 2623, "Smith County": 2624,
        "Stewart County": 2625, "Sullivan County": 2626, "Sumner County": 2627, "Tipton County": 2628,
        "Trousdale County": 2629, "Unicoi County": 2630, "Union County": 2631, "Van Buren County": 2632,
        "Warren County": 2633, "Washington County": 2634, "Wayne County": 2635, "Weakley County": 2636,
        "White County": 2637, "Williamson County": 2638, "Wilson County": 2639,
    }},
    "Texas": {"code": "TX", "counties": {
        "Anderson County": 2640, "Andrews County": 2641, "Angelina County": 2642, "Aransas County": 2643,
        "Archer County": 2644, "Armstrong County": 2645, "Atascosa County": 2646, "Austin County": 2647,
        "Bailey County": 2648, "Bandera County": 2649, "Bastrop County": 2650, "Baylor County": 2651,
        "Bee County": 2652, "Bell County": 2653, "Bexar County": 2654, "Blanco County": 2655,
        "Borden County": 2656, "Bosque County": 2657, "Bowie County": 2658, "Brazoria County": 2659,
        "Brazos County": 2660, "Brewster County": 2661, "Briscoe County": 2662, "Brooks County": 2663,
        "Brown County": 2664, "Burleson County": 2665, "Burnet County": 2666, "Caldwell County": 2667,
        "Calhoun County": 2668, "Callahan County": 2669, "Cameron County": 2670, "Camp County": 2671,
        "Carson County": 2672, "Cass County": 2673, "Castro County": 2674, "Chambers County": 2675,
        "Cherokee County": 2676, "Childress County": 2677, "Clay County": 2678, "Cochran County": 2679,
        "Coke County": 2680, "Coleman County": 2681, "Collin County": 2682, "Collingsworth County": 2683,
        "Colorado County": 2684, "Comal County": 2685, "Comanche County": 2686, "Concho County": 2687,
        "Cooke County": 2688, "Coryell County": 2689, "Cottle County": 2690, "Crane County": 2691,
        "Crockett County": 2692, "Crosby County": 2693, "Culberson County": 2694, "Dallam County": 2695,
        "Dallas County": 2696, "Dawson County": 2697, "Deaf Smith County": 2698, "Delta County": 2699,
        "Denton County": 2700, "DeWitt County": 2701, "Dickens County": 2702, "Dimmit County": 2703,
        "Donley County": 2704, "Duval County": 2705, "Eastland County": 2706, "Ector County": 2707,
        "Edwards County": 2708, "El Paso County": 2710, "Ellis County": 2709, "Erath County": 2711,
        "Falls County": 2712, "Fannin County": 2713, "Fayette County": 2714, "Fisher County": 2715,
        "Floyd County": 2716, "Foard County": 2717, "Fort Bend County": 2718, "Franklin County": 2719,
        "Freestone County": 2720, "Frio County": 2721, "Gaines County": 2722, "Galveston County": 2723,
        "Garza County": 2724, "Gillespie County": 2725, "Glasscock County": 2726, "Goliad County": 2727,
        "Gonzales County": 2728, "Gray County": 2729, "Grayson County": 2730, "Gregg County": 2731,
        "Grimes County": 2732, "Guadalupe County": 2733, "Hale County": 2734, "Hall County": 2735,
        "Hamilton County": 2736, "Hansford County": 2737, "Hardeman County": 2738, "Hardin County": 2739,
        "Harris County": 2740, "Harrison County": 2741, "Hartley County": 2742, "Haskell County": 2743,
        "Hays County": 2744, "Hemphill County": 2745, "Henderson County": 2746, "Hidalgo County": 2747,
        "Hill County": 2748, "Hockley County": 2749, "Hood County": 2750, "Hopkins County": 2751,
        "Houston County": 2752, "Howard County": 2753, "Hudspeth County": 2754, "Hunt County": 2755,
        "Hutchinson County": 2756, "Irion County": 2757, "Jack County": 2758, "Jackson County": 2759,
        "Jasper County": 2760, "Jeff Davis County": 2761, "Jefferson County": 2762, "Jim Hogg County": 2763,
        "Jim Wells County": 2764, "Johnson County": 2765, "Jones County": 2766, "Karnes County": 2767,
        "Kaufman County": 2768, "Kendall County": 2769, "Kenedy County": 2770, "Kent County": 2771,
        "Kerr County": 2772, "Kimble County": 2773, "King County": 2774, "Kinney County": 2775,
        "Kleberg County": 2776, "Knox County": 2777, "La Salle County": 2781, "Lamar County": 2778,
        "Lamb County": 2779, "Lampasas County": 2780, "Lavaca County": 2782, "Lee County": 2783,
        "Leon County": 2784, "Liberty County": 2785, "Limestone County": 2786, "Lipscomb County": 2787,
        "Live Oak County": 2788, "Llano County": 2789, "Loving County": 2790, "Lubbock County": 2791,
        "Lynn County": 2792, "Madison County": 2796, "Marion County": 2797, "Martin County": 2798,
        "Mason County": 2799, "Matagorda County": 2800, "Maverick County": 2801, "McCulloch County": 2793,
        "McLennan County": 2794, "McMullen County": 2795, "Medina County": 2802, "Menard County": 2803,
        "Midland County": 2804, "Milam County": 2805, "Mills County": 2806, "Mitchell County": 2807,
        "Montague County": 2808, "Montgomery County": 2809, "Moore County": 2810, "Morris County": 2811,
        "Motley County": 2812, "Nacogdoches County": 2813, "Navarro County": 2814, "Newton County": 2815,
        "Nolan County": 2816, "Nueces County": 2817, "Ochiltree County": 2818, "Oldham County": 2819,
        "Orange County": 2820, "Palo Pinto County": 2821, "Panola County": 2822, "Parker County": 2823,
        "Parmer County": 2824, "Pecos County": 2825, "Polk County": 2826, "Potter County": 2827,
        "Presidio County": 2828, "Rains County": 2829, "Randall County": 2830, "Reagan County": 2831,
        "Real County": 2832, "Red River County": 2833, "Reeves County": 2834, "Refugio County": 2835,
        "Roberts County": 2836, "Robertson County": 2837, "Rockwall County": 2838, "Runnels County": 2839,
        "Rusk County": 2840, "Sabine County": 2841, "San Augustine County": 2842, "San Jacinto County": 2843,
        "San Patricio County": 2844, "San Saba County": 2845, "Schleicher County": 2846, "Scurry County": 2847,
        "Shackelford County": 2848, "Shelby County": 2849, "Sherman County": 2850, "Smith County": 2851,
        "Somervell County": 2852, "Starr County": 2853, "Stephens County": 2854, "Sterling County": 2855,
        "Stonewall County": 2856, "Sutton County": 2857, "Swisher County": 2858, "Tarrant County": 2859,
        "Taylor County": 2860, "Terrell County": 2861, "Terry County": 2862, "Throckmorton County": 2863,
        "Titus County": 2864, "Tom Green County": 2865, "Travis County": 2866, "Trinity County": 2867,
        "Tyler County": 2868, "Upshur County": 2869, "Upton County": 2870, "Uvalde County": 2871,
        "Val Verde County": 2872, "Van Zandt County": 2873, "Victoria County": 2874, "Walker County": 2875,
        "Waller County": 2876, "Ward County": 2877, "Washington County": 2878, "Webb County": 2879,
        "Wharton County": 2880, "Wheeler County": 2881, "Wichita County": 2882, "Wilbarger County": 2883,
        "Willacy County": 2884, "Williamson County": 2885, "Wilson County": 2886, "Winkler County": 2887,
        "Wise County": 2888, "Wood County": 2889, "Yoakum County": 2890, "Young County": 2891,
        "Zapata County": 2892, "Zavala County": 2893,
    }},
    "Utah": {"code": "UT", "counties": {}},
    "Vermont": {"code": "VT", "counties": {}},
    "Virginia": {"code": "VA", "counties": {
        "Accomack County": 2937, "Albemarle County": 2938, "Alexandria": 3032, "Alleghany County": 2939,
        "Amelia County": 2940, "Amherst County": 2941, "Appomattox County": 2942, "Arlington County": 2943,
        "Augusta County": 2944, "Bath County": 2945, "Bedford County": 2946, "Bland County": 2947,
        "Botetourt County": 2948, "Bristol": 3034, "Brunswick County": 2949, "Buchanan County": 2950,
        "Buckingham County": 2951, "Buena Vista": 3035, "Campbell County": 2952, "Caroline County": 2953,
        "Carroll County": 2954, "Charles City": 2955, "Charlotte County": 2956, "Charlottesville": 3036,
        "Chesapeake": 3037, "Chesterfield County": 2957, "Clarke County": 2958, "Colonial Heights": 3038,
        "Covington": 3039, "Craig County": 2959, "Culpeper County": 2960, "Cumberland County": 2961,
        "Danville": 3040, "Dickenson County": 2962, "Dinwiddie County": 2963, "Emporia": 3041,
        "Essex County": 2964, "Fairfax City": 3042, "Fairfax County": 2965, "Falls Church": 3043,
        "Fauquier County": 2966, "Floyd County": 2967, "Fluvanna County": 2968, "Franklin City": 3044,
        "Franklin County": 2969, "Frederick County": 2970, "Fredericksburg": 3045, "Galax": 3046,
        "Giles County": 2971, "Gloucester County": 2972, "Goochland County": 2973, "Grayson County": 2974,
        "Greene County": 2975, "Greensville County": 2976, "Halifax County": 2977, "Hampton": 3047,
        "Hanover County": 2978, "Harrisonburg": 3048, "Henrico County": 2979, "Henry County": 2980,
        "Highland County": 2981, "Hopewell": 3049, "Isle of Wight County": 2982, "James City": 2983,
        "King & Queen County": 2984, "King George County": 2985, "King William County": 2986,
        "Lancaster County": 2987, "Lee County": 2988, "Lexington": 3050, "Loudoun County": 2989,
        "Louisa County": 2990, "Lunenburg County": 2991, "Lynchburg": 3051, "Madison County": 2992,
        "Manassas": 3052, "Manassas Park": 3053, "Martinsville": 3054, "Mathews County": 2993,
        "Mecklenburg County": 2994, "Middlesex County": 2995, "Montgomery County": 2996, "Nelson County": 2997,
        "New Kent County": 2998, "Newport News": 3055, "Norfolk": 3056, "Northampton County": 2999,
        "Northumberland County": 3000, "Norton": 3057, "Nottoway County": 3001, "Orange County": 3002,
        "Page County": 3003, "Patrick County": 3004, "Petersburg": 3058, "Pittsylvania County": 3005,
        "Poquoson": 3059, "Portsmouth": 3060, "Powhatan County": 3006, "Prince Edward County": 3007,
        "Prince George County": 3008, "Prince William County": 3009, "Pulaski County": 3010, "Radford": 3061,
        "Rappahannock County": 3011, "Richmond City": 3062, "Richmond County": 3012, "Roanoke City": 3063,
        "Roanoke County": 3013, "Rockbridge County": 3014, "Rockingham County": 3015, "Russell County": 3016,
        "Salem": 3064, "Scott County": 3017, "Shenandoah County": 3018, "Smyth County": 3019,
        "Southampton County": 3020, "Spotsylvania County": 3021, "Stafford County": 3022, "Staunton": 3065,
        "Suffolk": 3066, "Surry County": 3023, "Sussex County": 3024, "Tazewell County": 3025,
        "Virginia Beach": 3067, "Warren County": 3026, "Washington County": 3027, "Waynesboro": 3068,
        "Westmoreland County": 3028, "Williamsburg": 3069, "Winchester": 3070, "Wise County": 3029,
        "Wythe County": 3030, "York County": 3031,
    }},
    "Washington": {"code": "WA", "counties": {
        "Adams County": 3071, "Asotin County": 3072, "Benton County": 3073, "Chelan County": 3074,
        "Clallam County": 3075, "Clark County": 3076, "Columbia County": 3077, "Cowlitz County": 3078,
        "Douglas County": 3079, "Ferry County": 3080, "Franklin County": 3081, "Garfield County": 3082,
        "Grant County": 3083, "Grays Harbor County": 3084, "Island County": 3085, "Jefferson County": 3086,
        "King County": 118, "Kitsap County": 3087, "Kittitas County": 3088, "Klickitat County": 3089,
        "Lewis County": 3090, "Lincoln County": 3091, "Mason County": 3092, "Okanogan County": 3093,
        "Pacific County": 3094, "Pend Oreille County": 3095, "Pierce County": 3096, "San Juan County": 3097,
        "Skagit County": 3098, "Skamania County": 3099, "Snohomish County": 2, "Spokane County": 3100,
        "Stevens County": 3101, "Thurston County": 3102, "Wahkiakum County": 3103, "Walla Walla County": 3104,
        "Whatcom County": 3105, "Whitman County": 3106, "Yakima County": 3107,
    }},
    "West Virginia": {"code": "WV", "counties": {}},
    "Wisconsin": {"code": "WI", "counties": {}},
    "Wyoming": {"code": "WY", "counties": {}},
}


top_30_counties = [
    ("Los Angeles County", "California", 321),        # Rank 1  ~9.76M
    ("Cook County", "Illinois", 727),                 # Rank 2  ~5.18M
    ("Harris County", "Texas", 2740),                 # Rank 3  ~5.01M
    ("Maricopa County", "Arizona", 220),              # Rank 4  ~4.67M
    ("San Diego County", "California", 339),          # Rank 5  ~3.30M
    ("Orange County", "California", 332),             # Rank 6  ~3.17M
    ("Miami Dade County", "Florida", 479),            # Rank 7  ~2.84M
    ("Dallas County", "Texas", 2696),                 # Rank 8  ~2.66M
    ("Kings County", "New York", 1968),               # Rank 9  ~2.62M
    ("Riverside County", "California", 335),          # Rank 10 ~2.53M
    ("King County", "Washington", 118),               # Rank 12 ~2.34M
    ("Queens County", "New York", 1985),              # Rank 13 ~2.32M
    ("Tarrant County", "Texas", 2859),                # Rank 14 ~2.23M
    ("San Bernardino County", "California", 338),     # Rank 15 ~2.21M
    ("Bexar County", "Texas", 2654),                  # Rank 16 ~2.13M
    ("Broward County", "Florida", 442),               # Rank 17 ~2.04M
    ("Santa Clara County", "California", 345),        # Rank 18 ~1.93M
    ("Wayne County", "Michigan", 1429),               # Rank 19 ~1.77M
    ("Middlesex County", "Massachusetts", 1342),      # Rank 20 ~1.67M
    ("New York County", "New York", 1975),            # Rank 21 ~1.66M
    ("Alameda County", "California", 303),            # Rank 22 ~1.65M
    ("Palm Beach County", "Florida", 486),            # Rank 24 ~1.58M
    ("Hillsborough County", "Florida", 464),          # Rank 25 ~1.58M
    ("Philadelphia County", "Pennsylvania", 2411),    # Rank 26 ~1.57M
    ("Suffolk County", "New York", 1996),             # Rank 27 ~1.54M
    ("Orange County", "Florida", 484),                # Rank 28 ~1.53M
    ("Nassau County", "New York", 1974),              # Rank 29 ~1.39M
    ("Bronx County", "New York", 1947),               # Rank 30 ~1.38M
]

In [6]:
final_ads = []

# Build a lookup: county name -> state code
state_code_lookup = {state: data["code"] for state, data in us_data.items()}

def safe_text(el, default=None):
    return el.get_text(strip=True) if el else default

def safe_attr(el, attr, default=None):
    return el.get(attr) if el and el.has_attr(attr) else default


for county, state, county_id in top_30_counties:
    state_code = state_code_lookup[state]
    for page in range(1, 10):
        url = f'https://www.redfin.com/county/{county_id}/{state_code}/{county.replace(" ", "-")}/filter/sort=lo-days/page-{page}'
        # print(url)
        r = requests.get(url, headers=headers)
        soup = BeautifulSoup(r.content, 'lxml')
        ads = soup.find_all('div', class_='bp-mobileListHomeCard')

        for ad in ads:
            state = state
            state_code = state_code
            county = county
            relative_url = safe_attr(ad.find('a'), 'href')
            city = relative_url.split('/')[2] if relative_url else None
            img = safe_attr(ad.find('img'), 'src')
            price = safe_text(ad.find('div', class_='bp-Homecard__Price'))
            bedrooms = safe_text(ad.find('span', class_='bp-Homecard__Stats--beds'))
            bathrooms = safe_text(ad.find('span', class_='bp-Homecard__Stats--baths'))
            area = safe_text(ad.find('span', class_='bp-Homecard__Stats--sqft'))
            address = safe_text(ad.find('a'))
            final_ads.append({'state': state, 'county': county, 'state_code': state_code,
                            'city': city, 'img': img, 'price': price, 'bedrooms': bedrooms,
                            'bathrooms': bathrooms, 'area': area, 'address': address,
                            'relative_url': relative_url})
            
    break

df = pd.DataFrame(final_ads)
df = df.dropna(subset=['price']).reset_index(drop=True)
df

,state,county,state_code,city,img,price,bedrooms,bathrooms,area,address,relative_url
0,California,Los Angeles County,CA,Rancho-Palos-Verdes,https://ssl.cdn-redfin.com/photo/45/islphoto/8...,"$995,000",3 beds,2.5 baths,"1,476sq ft","28191 Ridgecove Ct S, Rancho Palos Verdes, CA ...",/CA/Rancho-Palos-Verdes/28191-Ridgecove-Ct-S-9...
1,California,Los Angeles County,CA,Valencia,https://ssl.cdn-redfin.com/photo/201/islphoto/...,"$1,149,999",4 beds,2.5 baths,"2,096sq ft","27015 Littlefield Dr, Valencia, CA 91354",/CA/Valencia/27015-Littlefield-Dr-91354/home/5...
2,California,Los Angeles County,CA,Canyon-Country,https://ssl.cdn-redfin.com/photo/45/islphoto/7...,"$998,000",5 beds,4 baths,"3,619sq ft","15503 Megan Dr, Canyon Country, CA 91387",/CA/Canyon-Country/15503-Megan-Dr-91387/home/1...
3,California,Los Angeles County,CA,Newhall,https://ssl.cdn-redfin.com/photo/45/islphoto/0...,"$649,000",2 beds,2.5 baths,"1,206sq ft","25219 Vermont, Newhall, CA 91321",/CA/Newhall/25219-Vermont-Dr-91321/home/6003487
4,California,Los Angeles County,CA,Alhambra,https://ssl.cdn-redfin.com/photo/45/islphoto/1...,"$1,098,000",3 beds,2 baths,"1,914sq ft","429 S Cordova St, Alhambra, CA 91801",/CA/Alhambra/429-S-Cordova-St-91801/home/7021657
...,...,...,...,...,...,...,...,...,...,...,...
334,California,Los Angeles County,CA,Los-Angeles,https://ssl.cdn-redfin.com/photo/40/islphoto/3...,"$725,000",2 beds,2 baths,"1,428sq ft","2700 Cahuenga Blvd #4319, Los Angeles, CA 90068",/CA/Los-Angeles/2700-Cahuenga-Blvd-E-90068/uni...
335,California,Los Angeles County,CA,Los-Angeles,https://ssl.cdn-redfin.com/photo/40/islphoto/3...,"$1,078,000",4 beds,3 baths,"2,000sq ft","2400 W 74th St, Los Angeles, CA 90043",/CA/Los-Angeles/2400-W-74th-St-90043/home/6422154
336,California,Los Angeles County,CA,Playa-del-Rey,https://ssl.cdn-redfin.com/photo/40/islphoto/9...,"$5,995,000",3 beds,3 baths,"5,476sq ft","147 Napoleon St, Playa Del Rey, CA 90293",/CA/Playa-del-Rey/147-Napoleon-St-90293/home/6...
337,California,Los Angeles County,CA,Los-Angeles,https://ssl.cdn-redfin.com/photo/40/islphoto/4...,"$195,000",— beds,— baths,—sq ft,"2560 N Hines Dr, Los Angeles, CA 90065",/CA/Los-Angeles/2560-Hines-Dr-90065/home/21925243
338,California,Los Angeles County,CA,Tujunga,https://ssl.cdn-redfin.com/photo/40/islphoto/4...,"$499,000",3 beds,2 baths,"1,150sq ft","7716 Grove St, Tujunga, CA 91042",/CA/Tujunga/7716-Grove-St-91042/home/5506107

In [7]:
df2 = clean(df).sort_values(by='state').reset_index(drop=True)
df2.head()

,state,county,state_code,city,img,price,bedrooms,bathrooms,area,address,relative_url,unit,url,area_m2,price_per_m2,source,query_date
0,California,Los Angeles County,CA,Rancho-Palos-Verdes,https://ssl.cdn-redfin.com/photo/45/islphoto/8...,995000,3.0,2.5,1476.0,"28191 Ridgecove Ct S, Rancho Palos Verdes, CA ...",/CA/Rancho-Palos-Verdes/28191-Ridgecove-Ct-S-9...,sq ft,https://www.redfin.com/CA/Rancho-Palos-Verdes/...,137.12,7256.42,redfin,2026-04-19
1,California,Los Angeles County,CA,South-Pasadena,https://ssl.cdn-redfin.com/photo/45/islphoto/7...,1388000,2.0,3.0,1858.0,"518 Garfield Ave Unit A, South Pasadena, CA 91030",/CA/South-Pasadena/518-Garfield-Ave-91030/unit...,sq ft,https://www.redfin.com/CA/South-Pasadena/518-G...,172.61,8041.25,redfin,2026-04-19
2,California,Los Angeles County,CA,Los-Angeles,https://ssl.cdn-redfin.com/photo/45/islphoto/7...,999900,2.0,3.0,1096.0,"1205 Cole, Los Angeles, CA 90038",/CA/Los-Angeles/1205-Cole-Ave-90038/home/7107727,sq ft,https://www.redfin.com/CA/Los-Angeles/1205-Col...,101.82,9820.27,redfin,2026-04-19
3,California,Los Angeles County,CA,Claremont,https://ssl.cdn-redfin.com/photo/45/islphoto/3...,1038500,3.0,2.0,2117.0,"1192 Briarcroft Rd, Claremont, CA 91711",/CA/Claremont/1192-Briarcroft-Rd-91711/home/78...,sq ft,https://www.redfin.com/CA/Claremont/1192-Briar...,196.68,5280.15,redfin,2026-04-19
4,California,Los Angeles County,CA,Los-Angeles,https://ssl.cdn-redfin.com/photo/45/islphoto/7...,739000,4.0,2.0,1236.0,"3815 Paloma, Los Angeles, CA 90011",/CA/Los-Angeles/3815-Paloma-St-90011/home/6925491,sq ft,https://www.redfin.com/CA/Los-Angeles/3815-Pal...,114.83,6435.60,redfin,2026-04-19

In [124]:
df2.to_csv("real_estate_usa.csv", sep=";", index=False, encoding="utf-8-sig")

In [77]:
base_url = "https://www.redfin.com/sitemap/"
final_map = []
for key, value in states.items():
    url = base_url + value
    r = requests.get(url, headers=headers)
    soup = BeautifulSoup(r.content, 'lxml')
    items = soup.find('ul', class_='list ldpsSection').find_all('li')
    for item in items:
        url = item.find('a')['href']
        city = item.find('a').get_text(strip=True)
        final_map.append({'state': key, 'state_code': value, 'city': city, 'url': url})

    break
final_map

AttributeError: 'NoneType' object has no attribute 'find_all'

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
# from curl_cffi import requests

import requests

cookies = {
    'feature_ab_tests': 'EXPO3198@7=unassigned|EXPO1555@55=GALLERY_ENTRY_LOADER_ON',
    'expclientform': 'eyJjb250YWN0cyI6IjEiLCJ0b3BpY0lkIjoiMyJ9',
    'expstate': 'H4sIAAAAAAAA/x2PyW6DMBRFfwkMRKVSFjRhMKpNQ20obCJsI2wCJCoh1Hx9geUd3tF9lARv1wK4kwiDVoSpFKF/fK91fOOrAduHwYes+zzFI1PwADssq7CboJoV76lK+lKyCG/5nWl4EFFslt+zqkL3Cdu7ymlGtm7Z2ypR8VfdB/ttmfubXopcPphyDJGbXglMWeXztI557nywd/CF/gW7DjcG/MXnW4MItZD2ND43GhMI4GAcryxKR9HTfb1R5WbHrVSyH08lrW/hpQGI+DZqoY2XYoRDptlp/Ui5XR19vDigL0SKGS3cScjF2Yj/54yxlxwBAAA=',
    'consent_status': 'false',
    'ssoOptimizelyUniqueVisitorId': 'e226bae5-50bd-4d14-a812-fbb19e056f6b',
    'optimizelyEndUserId': 'oeu1778410229581r0.9251855624515898',
    'is24_search_experiment_activated': 'SEA-6788_2%3Dredesign-off',
    'IS24VisitIdSC': 'sidcc2cdb00-a938-44d7-a987-87f104aabb3a',
    'IS24VisitId': 'vid2d721721-becd-40ae-a69a-1eb0e4bf75be',
    'websessionid': '0B606C20453D3D25F7F1C189B1D72E4C',
    'g_csrf_token': '54565d977224c29ff6829248382c46ae',
    'g_state': '{"i_l":0,"i_ll":1778610337823,"i_b":"llm7KM5/sOs7QvYQXWD3+SUQLf1hUhErFTSC9M0Fw2Y","i_e":{"enable_itp_optimization":0},"i_et":1777056882517}',
    'SSO-HMAC': 'w9Y8WGzcNK33mI_hPs-KqRaV-0peGYvB-PW_y1ah8Hw',
    'longUnreliableState': 'dWlkcg==:bS01OTkxODE5Mw==',
    'AWSALB': 'PJ5pYPfP/d4CKGCwhEYkDL78K8mU262ndy8fH+eLlYXlxv2B57omC4A5aMdrmyCLGxbliCDaHzpokhCiwBMhzU4eFgG5wZ3hTwhrm6dOpI6i1lI3LUIvm41AZYm9',
    'AWSALBCORS': 'PJ5pYPfP/d4CKGCwhEYkDL78K8mU262ndy8fH+eLlYXlxv2B57omC4A5aMdrmyCLGxbliCDaHzpokhCiwBMhzU4eFgG5wZ3hTwhrm6dOpI6i1lI3LUIvm41AZYm9',
    'SSO': 'KhcAAAEAS9077zHMpN90kcFO1qsHtQ5MySdoQGgi3MN0gIdEnQzk-pktnZrjQbhkfmIYAj2SYgVGhJY7ZTbwM9-dLU7xiu4Oz3RibgD1qIEmQP7-r3uRF6Vz8IJcquQWo4TCIuaFifYuTknnWDzGmpSYsZ4BFe12pVGbqFiT49qb6GKPxgilJ-wLpt92397IPcpKMGB_OHiMTm4jdcvJEpXGDA_ua_bRBP5WAY3FoDaCQ5gmLHt86mtw60A3DAOR_GK7fows_GwEFeRunuGjsoyb6yL923d1sF7trlLsYSuWfNf-hAX0XgOAfkJJi6C1nxB9BAMq0rLqV7NyhxVyJfefwY_yGAAAAA5rZXktMDUtMDYtMjAxMwAAAQBYkBI2tEw7rOXsFD66AGQPQsNheprOh38OsZGokWw6_WIU61u2SUXL6bO4Va_9e1HVBwKXj5HVQIoejpiwNy1VavOaeLjOca7cWr9SsHSLU_m8KYrCwS6rt6MkSjdOBPIWID-3C-VpYgGPIsvGcYUlcVriVD_SlXtT7cWnmXZX8PwjJdJMe2S_sJAQdjPyGpSig2hMwx2mqP2BNPAyIebBwyDCPVrkNiv89T0ed-ydmyqExtgp82-1jquDLSbMvFZ2nFxgE99UcHfeT-cmKvFheA63TUzSoUjfgW6jG5USFNOQkA7ry2S-dSDVijehmfBF7yTb4rP53akIboolJKmLAAAADmtleS0wNi0wNi0yMDEzAAABAI1_HaV_r_zqU6mks0qYPILpWfKz-WFjLFhcHtfszMZVtPlAAp01_VoeGKrEXxeGWzwZ6GWf8etRh6FKGobWkOhrht_7CRzOZxsMu4MHzRwZmu2zzvFG12oDgL7KAaq6zd3F_cJGXMSlUNwZFNcgMJWW4NZz2uoHNXhFTtEngUsGy2LcJ5JweGXQG9KGhxRtjCPo9-kJuaqgUApUe_Efs4hhal4mMWtMAscSIGQG1zKQcqYHF_bCBll-A8zj18mDRq9GqQiVpGfo6bSJEDOHWGpQfrsDXUob7CUdL5JHKIeqU1o48eT9y_Rzhk0qGwolPK-EdkmvWyKRl2AQ5Bv1ARM',
    'user-info': 'eyJzc29JZCI6MCwiZW1haWwiOiJzYWhpbi50dW1AZ21haWwuY29tIiwiY2FuSGlkZURwYUNoZWNrYm94Ijp0cnVlfQ==',
    'X-XSRF-TENANT-NETWORK-TOKEN': '89e8b484-78ee-4141-b2b6-cad9a631c535',
    'utag_main': 'v_id:019dc0d8239a0020439dc002c3040506f002106700bd8$_sn:4$_se:373$_ss:0$_st:1778613865999$ses_id:1778609552832%3Bexp-session$_pn:31%3Bexp-session$referrer_to_lp:%2F%3Bexp-session$geo_bln_session:nordrhein_westfalen%3Bexp-session$geo_krs_session:d%C3%BCsseldorf%3Bexp-session$enteredFrom:result_list%3Bexp-session$ga_cd_cxp_referrer:HYBRID_VIEW_MAP%3Bexp-session$survey_overlay:b%3Bexp-session$ga_cd_userrole_profile_status:basic',
    'aws-waf-token': '814de637-3a62-4a21-ba16-6907f9de1f4a:CQoAeq6Eu3AGAAAA:xEEANlZkl9t5wZxH3+08NpHy3XrGR+oCkWXcoQiqV3v+cLM0bJLoOuqoMOCFSTw/aqRAoWmjBi/zV5WeVsM2qN9HGC8/oLdrk2a3j7JH88G2FrpCSx5ppIutqxt/DtmnLh6tAfBXiY3hEROtl021RWUxP6AYrdYSb++eDLFIlsZl2rHoDShgdv39tG5OuueDpCllTwaNLq7oL9i4cheEwq09tH92yqlEHLzptBBDdLuP9Ntfut+UCe+qPYZfFnP7B1fafo+EkpC6XjeIDh1u',
}

headers = {
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'accept-language': 'de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,tr;q=0.6,hu;q=0.5',
    'cache-control': 'no-cache',
    'pragma': 'no-cache',
    'priority': 'u=0, i',
    'referer': 'https://www.immobilienscout24.de/Suche/de/nordrhein-westfalen/duesseldorf/wohnung-kaufen?rented=false&price=-250000.0&apartmenttypes=halfbasement,penthouse,other,loft,groundfloor,terracedflat,raisedgroundfloor,apartment,maisonette&bbox=X3Nsd0hzdmdoQHdpRD8-X3ZKdmlEPw..',
    'sec-ch-ua': '"Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36',
    # 'cookie': 'feature_ab_tests=EXPO3198@7=unassigned|EXPO1555@55=GALLERY_ENTRY_LOADER_ON; expclientform=eyJjb250YWN0cyI6IjEiLCJ0b3BpY0lkIjoiMyJ9; expstate=H4sIAAAAAAAA/x2PyW6DMBRFfwkMRKVSFjRhMKpNQ20obCJsI2wCJCoh1Hx9geUd3tF9lARv1wK4kwiDVoSpFKF/fK91fOOrAduHwYes+zzFI1PwADssq7CboJoV76lK+lKyCG/5nWl4EFFslt+zqkL3Cdu7ymlGtm7Z2ypR8VfdB/ttmfubXopcPphyDJGbXglMWeXztI557nywd/CF/gW7DjcG/MXnW4MItZD2ND43GhMI4GAcryxKR9HTfb1R5WbHrVSyH08lrW/hpQGI+DZqoY2XYoRDptlp/Ui5XR19vDigL0SKGS3cScjF2Yj/54yxlxwBAAA=; consent_status=false; ssoOptimizelyUniqueVisitorId=e226bae5-50bd-4d14-a812-fbb19e056f6b; optimizelyEndUserId=oeu1778410229581r0.9251855624515898; is24_search_experiment_activated=SEA-6788_2%3Dredesign-off; IS24VisitIdSC=sidcc2cdb00-a938-44d7-a987-87f104aabb3a; IS24VisitId=vid2d721721-becd-40ae-a69a-1eb0e4bf75be; websessionid=0B606C20453D3D25F7F1C189B1D72E4C; g_csrf_token=54565d977224c29ff6829248382c46ae; g_state={"i_l":0,"i_ll":1778610337823,"i_b":"llm7KM5/sOs7QvYQXWD3+SUQLf1hUhErFTSC9M0Fw2Y","i_e":{"enable_itp_optimization":0},"i_et":1777056882517}; SSO-HMAC=w9Y8WGzcNK33mI_hPs-KqRaV-0peGYvB-PW_y1ah8Hw; longUnreliableState=dWlkcg==:bS01OTkxODE5Mw==; AWSALB=PJ5pYPfP/d4CKGCwhEYkDL78K8mU262ndy8fH+eLlYXlxv2B57omC4A5aMdrmyCLGxbliCDaHzpokhCiwBMhzU4eFgG5wZ3hTwhrm6dOpI6i1lI3LUIvm41AZYm9; AWSALBCORS=PJ5pYPfP/d4CKGCwhEYkDL78K8mU262ndy8fH+eLlYXlxv2B57omC4A5aMdrmyCLGxbliCDaHzpokhCiwBMhzU4eFgG5wZ3hTwhrm6dOpI6i1lI3LUIvm41AZYm9; SSO=KhcAAAEAS9077zHMpN90kcFO1qsHtQ5MySdoQGgi3MN0gIdEnQzk-pktnZrjQbhkfmIYAj2SYgVGhJY7ZTbwM9-dLU7xiu4Oz3RibgD1qIEmQP7-r3uRF6Vz8IJcquQWo4TCIuaFifYuTknnWDzGmpSYsZ4BFe12pVGbqFiT49qb6GKPxgilJ-wLpt92397IPcpKMGB_OHiMTm4jdcvJEpXGDA_ua_bRBP5WAY3FoDaCQ5gmLHt86mtw60A3DAOR_GK7fows_GwEFeRunuGjsoyb6yL923d1sF7trlLsYSuWfNf-hAX0XgOAfkJJi6C1nxB9BAMq0rLqV7NyhxVyJfefwY_yGAAAAA5rZXktMDUtMDYtMjAxMwAAAQBYkBI2tEw7rOXsFD66AGQPQsNheprOh38OsZGokWw6_WIU61u2SUXL6bO4Va_9e1HVBwKXj5HVQIoejpiwNy1VavOaeLjOca7cWr9SsHSLU_m8KYrCwS6rt6MkSjdOBPIWID-3C-VpYgGPIsvGcYUlcVriVD_SlXtT7cWnmXZX8PwjJdJMe2S_sJAQdjPyGpSig2hMwx2mqP2BNPAyIebBwyDCPVrkNiv89T0ed-ydmyqExtgp82-1jquDLSbMvFZ2nFxgE99UcHfeT-cmKvFheA63TUzSoUjfgW6jG5USFNOQkA7ry2S-dSDVijehmfBF7yTb4rP53akIboolJKmLAAAADmtleS0wNi0wNi0yMDEzAAABAI1_HaV_r_zqU6mks0qYPILpWfKz-WFjLFhcHtfszMZVtPlAAp01_VoeGKrEXxeGWzwZ6GWf8etRh6FKGobWkOhrht_7CRzOZxsMu4MHzRwZmu2zzvFG12oDgL7KAaq6zd3F_cJGXMSlUNwZFNcgMJWW4NZz2uoHNXhFTtEngUsGy2LcJ5JweGXQG9KGhxRtjCPo9-kJuaqgUApUe_Efs4hhal4mMWtMAscSIGQG1zKQcqYHF_bCBll-A8zj18mDRq9GqQiVpGfo6bSJEDOHWGpQfrsDXUob7CUdL5JHKIeqU1o48eT9y_Rzhk0qGwolPK-EdkmvWyKRl2AQ5Bv1ARM; user-info=eyJzc29JZCI6MCwiZW1haWwiOiJzYWhpbi50dW1AZ21haWwuY29tIiwiY2FuSGlkZURwYUNoZWNrYm94Ijp0cnVlfQ==; X-XSRF-TENANT-NETWORK-TOKEN=89e8b484-78ee-4141-b2b6-cad9a631c535; utag_main=v_id:019dc0d8239a0020439dc002c3040506f002106700bd8$_sn:4$_se:373$_ss:0$_st:1778613865999$ses_id:1778609552832%3Bexp-session$_pn:31%3Bexp-session$referrer_to_lp:%2F%3Bexp-session$geo_bln_session:nordrhein_westfalen%3Bexp-session$geo_krs_session:d%C3%BCsseldorf%3Bexp-session$enteredFrom:result_list%3Bexp-session$ga_cd_cxp_referrer:HYBRID_VIEW_MAP%3Bexp-session$survey_overlay:b%3Bexp-session$ga_cd_userrole_profile_status:basic; aws-waf-token=814de637-3a62-4a21-ba16-6907f9de1f4a:CQoAeq6Eu3AGAAAA:xEEANlZkl9t5wZxH3+08NpHy3XrGR+oCkWXcoQiqV3v+cLM0bJLoOuqoMOCFSTw/aqRAoWmjBi/zV5WeVsM2qN9HGC8/oLdrk2a3j7JH88G2FrpCSx5ppIutqxt/DtmnLh6tAfBXiY3hEROtl021RWUxP6AYrdYSb++eDLFIlsZl2rHoDShgdv39tG5OuueDpCllTwaNLq7oL9i4cheEwq09tH92yqlEHLzptBBDdLuP9Ntfut+UCe+qPYZfFnP7B1fafo+EkpC6XjeIDh1u',
}

params = {
    'referrer': 'HYBRID_VIEW_MAP',
    'searchId': '0eb8cd55-0426-3442-ad83-00cd2c75e29b',
    'searchType': 'district',
    'fairPrice': 'FAIR_OFFER',
}

response = requests.get('https://www.immobilienscout24.de/expose/166985004', params=params, headers=headers)

In [2]:
response.text

'<html><head> <meta http-equiv="content-type" content="text/html; charset=UTF-8"/> <meta http-equiv="X-UA-Compatible" content="IE=edge"/> <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1"/> <meta name="robots" content="noindex, nofollow"> <title>Ich bin kein Roboter - ImmobilienScout24</title> <link rel="icon" type="image/vnd.microsoft.icon" href="https://www.immobilienscout24.de/favicon.ico"/> <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="https://www.immobilienscout24.de/favicon.ico"/> <link href="https://www.static-immobilienscout24.de/fro/core/5.10.0/font/vendor/make-it-sans/MakeItSansIS24WEB-Regular.woff2" as="font" type="font/woff2" crossorigin=""> <link rel="stylesheet" type="text/css" href="https://www.static-immobilienscout24.de/fro/core/5.10.0/css/core.min.css" crossorigin=""> <script type="text/javascript" src="https://82d925f87a91.edge.sdk.awswaf.com/82d925f87a91/dc8cf73809de/challenge.js"></script></head><body><header class="page-header page-header--white"> <a href="https://www.immobilienscout24.de/" class="page-header__logo margin-left-xxl"> <img alt="ImmobilienScout24" src="https://www.static-immobilienscout24.de/fro/imperva/0.0.1/is24-logo.svg"> </a></header><div class="page-wrapper align-center margin-top-xxl"> <div class="main horizontal-center five-tenths"> <h1 class="align-center">Gleich gehtâ\x80\x99s weiter</h1> <div class="three-tenths horizontal-center palm-hide"> <img src="https://www.static-immobilienscout24.de/fro/imperva/0.0.1/robot-logo.svg" alt="Roboter Logo"> </div> <div class="font-bold margin-top-xl"> Wir Ã¼berprÃ¼fen schnell, dass du kein Roboter oder eine schÃ¤dliche Software bist. Damit schÃ¼tzen wir unsere Website und die Daten unserer Nutzerinnen und Nutzer vor betrÃ¼gerischen AktivitÃ¤ten. Du wirst in einigen Sekunden auf unsere Seite weitergeleitet. </div> <div class="container"> Um wieder Zugriff zu erhalten, stelle bitte sicher, dass Cookies und JavaScript aktiviert sind, bevor du die Seite neu lÃ¤dst. </div> <div id="message-container" class="margin-top-l status-message status-error hide"></div> <div class="font-bold margin-top-m">Warum fÃ¼hren wir diese SicherheitsmaÃ\x9fnahme durch?</div> <div>Mit dieser Methode stellen wir fest, dass du kein Roboter oder eine schÃ¤dliche Spam-Software bist. Damit schÃ¼tzen wir unsere Webseite und die Daten unserer Nutzerinnen und Nutzer vor betrÃ¼gerischen AktivitÃ¤ten. </div> <div class="font-bold margin-top-m">Warum haben wir deine Anfrage blockiert?</div> <div>Es kann verschiedene GrÃ¼nde haben, warum wir dich fÃ¤lschlicherweise als Roboter identifiziert haben. MÃ¶glicherweise </div> <ul class="list-bullet align-left margin-left-xl"> <li>hast du die Cookies fÃ¼r unsere Seite deaktiviert.</li> <li>hast du die AusfÃ¼hrung von JavaScript deaktiviert.</li> <li>nutzt du ein Browser-Plugin eines Drittanbieters, beispielsweise einen Ad-Blocker.</li> </ul> <div class="margin-top-l"><button class="button-secondary" id="reqBtn">Anfrage-ID anzeigen</button></div> </div></div><footer class="main-footer"> <a href="https://www.immobilienscout24.de/impressum.html">Impressum</a> <div class="legend margin-top"> Â© Copyright 1999 - 2024 Immobilien Scout GmbH </div></footer><script type="text/javascript"> const wl=window.location; document.querySelector("#reqBtn").addEventListener("click", (e)=> fetch("/gk-id/t").then(res => { e.target.parentElement.innerHTML="Anfrage-ID: " + res.headers.get(\'X-Amz-Cf-Id\'); }) ); let r=0; const id=setInterval(() => { r++; const awi=AwsWafIntegration; if (awi.hasToken()) { clearInterval(id); awi.saveReferrer(); if (wl.search.includes("wafforce")) { const url=new URL(wl); url.searchParams.delete("wafforce"); wl.href=url.toString(); } else { wl.reload(true); } } if (r > 50) { const c=document.querySelector("#message-container"); c.innerHTML="<h4>Es ist ein Fehler aufgetreten</h4><p>Bitte versuche es spÃ¤ter erneut.</p>"; c.classList.remove("hide"); } }, 200);</script></body></html>'